oaknational/oak-ai-lesson-assistant

- doppler.yaml
- Updates the Doppler project name in the doppler.yml file
> fix: doppler project name

- SECURITY.md
- Fixes broken link to [security.txt](https://www.thenational.academy/.well-known/security.txt)
> chore(sec): fix broken link

- packages/api/src/router/appSessions.ts
- Fixes chat history for users with a long chat history
- Cause: https://www.prisma.io/docs/accelerate/limitations#response-size-limit
- 5mb limit was being exceeded because so much data (every chat 'output') was being retrieved from database
https://www.notion.so/oaknationalacademy/Fix-s-chat-history-7ea2831b3b954a10ab38a3d3b0f9a72b?pvs=4
- history should still work
- ... once merged @hannah-bethclark should check history
> fix: large chat history

- apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
- apps/nextjs/src/components/AppComponents/Chat/export-buttons/LessonPlanProgressBar.tsx
- update mobile view progress bar to use the hook `useProgressForDownloads` 
- this fixes the bug where in mobile view it was still showing /12 sessions
> fix: mobile view progress

- apps/nextjs/src/app/aila/[id]/download/SurveyDialogLauncher.ts
- apps/nextjs/src/components/DialogControl/ContentOptions/EndOfLessonFeedback.tsx
- apps/nextjs/src/components/DialogControl/dialogStyles.ts
- apps/nextjs/src/components/Feedback/index.tsx
Fixes #
1. Go to https://oak-ai-lesson-assistant-g15q0h54x.vercel-preview.thenational.academy
{screenshots}
{screenshots}
> refactor: style the popup and reintroduce

- apps/nextjs/src/components/AppComponents/Chat/header.tsx
In the long run there might be a better pattern for this through the useDemoUser hook
> fix: fix flash of demo banner when loading

- apps/nextjs/src/app/aila/[id]/download/page.tsx
- fixes auth on Downloads page
> fix: downloads page auth check

- apps/nextjs/src/components/ContextProviders/AnalyticsProvider.tsx
- don't send user email to main PostHog
> fix: don't send user email to main PostHog

- apps/nextjs/src/components/ContextProviders/AnalyticsProvider.tsx
> chore: lint

- apps/nextjs/package.json
- apps/nextjs/src/app/home-page.tsx
- apps/nextjs/src/middlewares/csp.ts
- pnpm-lock.yaml
- Added two mux videos to the home page
1. Go to the home page
2. You should see a video that can. play in the hero and in the first section
> feat: add videos to home page

- apps/nextjs/src/components/AppComponents/Chat/drop-down-section/modify-button.tsx
The other button didn't allow the user to input anything in the modify button drop down.
This PR allows the user to input text
1. go to a lesson and create a section
2. Try and modify a section and select other
> fix: allow the user to input other text

- apps/nextjs/src/middlewares/csp.ts
Was seeing a lot of errors for the home page video from mux
> fix: add litix to csp

- packages/db/index.ts
- Adjusts how we initialise Prisma in the db package so that we don't have the "This is the 10th instance of Prisma - is that what you want?" warning
> fix: prisma init singleton

- apps/nextjs/src/components/DownloadButton.tsx
Fixes #
1. Go to {deployment_url}
{screenshots}
{screenshots}
> fix: email error message only on error

- apps/nextjs/src/components/AppComponents/Chat/clear-history.tsx
Fixes #
1. Go to https://oak-ai-lesson-assistant-2xh1ce24z.vercel-preview.thenational.academy
{screenshots}
{screenshots}
> fix: clear history button position

- apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
- Hotfix for a hotfix for today's release candidate
> fix: hotfix incorrect top position in mobile view

- apps/nextjs/src/components/AppComponents/Layout/index.tsx
Fixs:
https://www.notion.so/oaknationalacademy/Exports-Page-Overlap-59aa844dd8914c4f8ea52fe90d4a41a7
> fix: exports page overlap

- apps/nextjs/src/components/AppComponents/Chat/chat-lhs-header.tsx
Fixes:
List of changes](https://www.notion.so/oaknationalacademy/Remove-second-Aila-heading-5cb1eefc586143d4805b1f9c5cfb4fc3)
> chore: remove second aila heading

- apps/nextjs/src/components/AppComponents/Chat/chat-history.tsx
- apps/nextjs/src/components/AppComponents/Chat/header.tsx
Fixes paths for help fall back
> fix: correct paths for help

- apps/nextjs/src/app/aila/help/index.tsx
- apps/nextjs/src/components/AppComponents/Chat/chat-history.tsx
- apps/nextjs/src/components/AppComponents/Chat/header.tsx
> fix: help button

- apps/nextjs/.eslintrc.cjs
- apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
- apps/nextjs/src/hooks/surveys/usePosthogFeedbackSurvey.ts
- uses useAnalytics hook to access the correct instance of posthog
> fix: survey not found bug

- apps/nextjs/.eslintrc.cjs
- apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
- apps/nextjs/src/hooks/surveys/usePosthogFeedbackSurvey.ts
- cherry picked commit from main
> fix: survey not found bug (#121)

- README.md
- Updated the release process in the README.
> chore: update release process docs

- packages/aila/src/core/llm/OpenAIService.ts
- Adds a single line log that tells you how long the first token took to come back from Open AI
> feat: add time to first token for openai

- packages/aila/src/core/prompt/builders/AilaLessonPromptBuilder.ts
- packages/core/src/models/lessonPlans.ts
- packages/core/src/prompts/lesson-assistant/index.ts
- packages/core/src/prompts/lesson-assistant/parts/body.ts
- packages/core/src/prompts/lesson-assistant/parts/context.ts
- packages/core/src/prompts/lesson-assistant/parts/protocol.ts
- packages/core/src/prompts/lesson-assistant/parts/schema.ts
- packages/core/src/prompts/lesson-assistant/parts/signOff.ts
- packages/core/src/prompts/lesson-assistant/parts/task.ts
- packages/core/src/prompts/lesson-assistant/variants.ts
- I had to make some adjustments to the prompt logic for it to work correctly in 'generate' mode
> fix: 'generate' vs 'interactive' prompt fixes

- apps/nextjs/src/middleware.ts
- attempt to get more info on middleware exceptions
- PR'd as a hotfix because we're getting thousands of such events daily. However if you think this is a too liberal use of the hotfix release, then i'm all ears
> chore: 'extra' sentry error handling in middelware

- apps/nextjs/src/components/DialogControl/dialogStyles.ts
fixes:
https://www.notion.so/oaknationalacademy/Feedback-Form-Sizing-10426cc4e1b18022addddbdf27ec49f9?pvs=23
> fix: dialog window bug

- apps/nextjs/src/components/AppComponents/Chat/chat-history.tsx
fixes:
https://www.notion.so/oaknationalacademy/Aila-option-in-menu-518112e439414f96a0da7778d628f7c7
> fix: close sidebar on new lesson

- packages/ingest/package.json
- packages/ingest/src/captions/getCaptionsByFileName.ts
- packages/ingest/src/captions/getCaptionsFileNameForLesson.ts
- packages/ingest/src/import-lessons/graphql/client.ts
- packages/ingest/src/import-lessons/graphql/query.ts
- packages/ingest/tsconfig.json
- pnpm-lock.yaml
- Creates an empty package for the ingest service
- Adds graphql query for Oak lessons
- Adds functions (largely copied from OWA) for fetching captions
> chore: create empty ingest package

- apps/nextjs/src/components/AppComponents/Chat/sidebar-mobile.tsx
- apps/nextjs/src/components/AppComponents/Chat/sidebar.tsx
- apps/nextjs/tests-e2e/tests/aila-chat/flexible-prompt-live.test.ts
- apps/nextjs/tests-e2e/tests/sidebar.test.ts
The most minimal test possible to check that you can access a chat from the sidebar
> test: add an e2e test for the sidebar

- packages/db/prisma/migrations/20241008112505_ingest_foreign_keys/migration.sql
This should have gone in as part of a previous PR, but slipped off
> chore: migration to remove unused foreign keys

- apps/nextjs/tests-e2e/tests/aila-chat/helpers.ts
- packages/ingest/src/db-helpers/createErrorRecord.ts
- packages/ingest/src/db-helpers/loadLessonsAndUpdateState.ts
- packages/ingest/src/embedding/handleEmbeddingBatchSuccess.ts
- packages/ingest/src/embedding/startEmbedding.ts
- packages/ingest/src/generate-lesson-plans/handleLessonPlanBatchSuccess.ts
- packages/ingest/src/generate-lesson-plans/startGenerating.ts
- packages/ingest/src/openai-batches/customId.ts
- packages/ingest/src/openai-batches/getCustomIdsFromJsonlFile.ts
- packages/ingest/src/openai-batches/handleOpenAiBatchErrorFile.ts
- packages/ingest/src/openai-batches/startBatch.ts
- packages/ingest/src/openai-batches/submitOpenAiBatch.ts
- packages/ingest/src/openai-batches/writeBatchFile.ts
- a final round of helper changes before the pipeline step scripts
> chore: ingest helpers final changes

- packages/db/prisma/schema.prisma
- packages/ingest/src/config/ingestConfig.ts
- packages/ingest/src/db-helpers/createIngestRecord.ts
- packages/ingest/src/db-helpers/getIngestById.ts
- packages/ingest/src/fixtures/rawLesson.json
- packages/ingest/src/fixtures/userPrompt.txt
- packages/ingest/src/fixtures/userPromptTitleSubjectKeyStage.txt
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/exitQuiz.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/keyLearningPoints.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/keywords.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/learningOutcome.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/misconceptions.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/starterQuiz.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/titleSubjectKeyStage.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/toMarkdownList.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/transcript.promptPart.ts
- packages/ingest/src/generate-lesson-plans/user-prompt-parts/year.promptPart.ts
- adds ingest config column
- splits user prompt into parts (prompt will depend on config)
- add fixtures
> chore: add ingest config, split user prompt parts, add fixtures

- apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
- apps/nextjs/src/hooks/useTemporaryLessonPlanWithStreamingEdits.ts
Reverts oaknational/oak-ai-lesson-assistant#214. I accidentally clocked merge on the wrong PR and we don't have the merge protection enabled
> chore: "chore: refactor chat provider"

- apps/nextjs/src/lib/errors/getRootErrorCause.ts
- apps/nextjs/src/middleware.ts
- apps/nextjs/src/middlewares/middlewareErrorLogging.ts
> fix: middleware syntax recursive

- apps/nextjs/src/components/Onboarding/LegacyUpgradeNotice.tsx
fix: spacing on onboarding upgrade screen [AI-500]
> build: release

- packages/db/prisma/migrations/20241016113305_ingest_config/migration.sql
- adds a migration i should have added in the previous PR 
- this gets the migrations up to date with the schema on main
> fix: add migration for ingest config

- .github/workflows/playwright.yml
- apps/nextjs/playwright.config.ts
An extension to #224 to comment a useful playwright summary with a link to the hosted report
> build: update playwright comment

- packages/ingest/src/import-lessons/importLessonsFromOakDB.ts
- packages/ingest/src/index.ts
- packages/ingest/src/steps/0-start.ts
- packages/ingest/src/steps/1-captions.ts
- packages/ingest/src/steps/2-lp-batch-start.ts
- packages/ingest/src/steps/3-lp-batch-sync.ts
- packages/ingest/src/steps/4-lp-chunking.ts
- packages/ingest/src/steps/5-lp-parts-embed-start.ts
- packages/ingest/src/steps/6-lp-parts-embed-sync.ts
- packages/ingest/src/types.ts
- packages/ingest/src/utils/splitJsonlByRowsOrSize.ts
- use the logger, not the console
> chore: use ai logger in ingest service

- apps/nextjs/src/components/AppComponents/Chat/chat-start-form.tsx
- apps/nextjs/src/components/LoadingWheel.tsx
- Removes the white flash when the loading wheel appears by adding a visible attribute
> fix: remove flash when loading wheel appears

- apps/nextjs/package.json
- apps/nextjs/tsconfig.json
- apps/nextjs/tsconfig.storybook.json
- apps/nextjs/tsconfig.test.json
- package.json
- packages/aila/package.json
- packages/aila/tsconfig.json
- packages/aila/tsconfig.test.json
- packages/ingest/package.json
- packages/ingest/tsconfig.test.json
- tsconfig.test.json
- turbo.json
- Allows us to run tests sequentially in verbose mode
- Reduces CPU load and allows you to see test durations
> feat: add a test:seq command

- apps/nextjs/src/components/AppComponents/Chat/chat-lhs-header.tsx
- Fixes a small issue where we are showing the streaming status by incorrectly detecting the environment name
> fix: hide streaming status in production

- apps/nextjs/src/components/AppComponents/Chat/chat-start.tsx
- apps/nextjs/src/components/AppComponents/Chat/empty-screen-accordion.tsx
- Renames Empty Screen Accordian to Accordion
> fix: rename accordian to accordion

- apps/nextjs/src/ai-apps/quiz-designer/convertToGIFTFormat.ts
- apps/nextjs/src/app/actions.ts
- apps/nextjs/src/app/aila/help/index.tsx
- apps/nextjs/src/app/layout.tsx
- apps/nextjs/src/app/manifest.ts
- apps/nextjs/src/components/Feedback/index.tsx
- apps/nextjs/src/hooks/useDemoLocking.ts
- packages/api/src/middleware/adminAuth.ts
- packages/api/src/middleware/auth.ts
- packages/api/src/middleware/rateLimiter.ts
- packages/api/src/router/admin.ts
- packages/api/src/router/appSessions.ts
- packages/core/src/analytics/posthogAiBetaServerClient.ts
- packages/core/src/functions/generation/imageAltTextRequestGeneration.ts/requestImageDescription.ts
- packages/core/src/functions/slack/notifyRateLimit.ts
- packages/core/src/prompts/lesson-assistant/parts/interactingWithTheUser.ts
- packages/core/src/prompts/lesson-assistant/parts/protocol.ts
- packages/core/src/prompts/lesson-assistant/parts/schema.ts
- packages/core/src/prompts/lesson-planner/extend-lesson-plan-quiz/variants/main/parts/output.ts
- packages/core/src/prompts/lesson-planner/regenerate-lesson-plan/variants/main/parts/output.ts
- packages/core/src/scripts/import-new-lessons/importNewLessons.ts
- packages/core/src/workers/generations/requestGeneration.ts
- packages/ingest/src/import-lessons/graphql/client.ts
- packages/ingest/src/steps/0-start.ts
- Several string changes to match the new linting rules
> chore: linting strings to match the new linting rules

- packages/aila/src/core/chat/PatchEnqueuer.ts
- Removes the text encoder from the PatchEnqueuer
> chore: remove unused text encoder from PatchEnqueuer

- apps/nextjs/src/app/api/qd-download/route.ts
- The call to save the download event was not being awaited
> fix: await the save download event call

- apps/nextjs/src/components/AppComponents/Chat/chat-layout.tsx
- apps/nextjs/src/components/AppComponents/Chat/chat-left-hand-side.tsx
- apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
- Incrementally adding the useLessonChat hook in more places, removing some prop-drilling
> chore: use the chat context provider in more components

- apps/nextjs/src/lib/analytics/lessonPlanTrackingContext.tsx
- Adds missing dependencies to the lesson plan tracking context
> fix: add missing dependencies to lesson plan tracking context

- apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.tsx
- apps/nextjs/src/lib/lessonPlan/organiseSections.ts
- Makes organiseSections into a shared file
> chore: make organiseSections a shared file

- packages/core/src/models/lessonSnapshots.ts
- comment explaining what lesson snapshots are
> docs: comment on lesson snapshots model

- packages/core/src/prompts/lesson-assistant/parts/interactingWithTheUser.ts
- Currently we are logging the entire prompt "next step"
- This is useful, but this reduces logging to just the title of the step
> chore: reduce prompt step logging

- apps/nextjs/src/app/api/cron-jobs/expired-exports/route.ts
Google drive delete cron job is throwing errors from Prisma, 
-  Update each record 1 at a time to identify [error](https://oak-national-academy.sentry.io/issues/11846058/?alert_rule_id=2299&alert_type=issue&environment=production&notification_uuid=accb24d2-7777-4df8-a3f3-f031453a52a0&project=4507089597300816&referrer=slack) with specific id's
- Allow job to continue to delete files when an id is not found in the database and report missing ids at the end with error
How to test: (comment out auth)
http://localhost:2525/api/cron-jobs/expired-exports
https://www.notion.so/oaknationalacademy/Google-Drive-file-deletion-cron-job-14426cc4e1b180b1bf88dd8d2c566ad1
> refactor: add more granular logging to cron job

- packages/db/package.json
- packages/db/prisma/migrations/20241126121910_ingest_rag_published_index/migration.sql
- packages/db/prisma/schema.prisma
Adds
- isPublished
- oakLessonSlug
to rag lesson plan schema. Adds migration for it too.
> chore: add rag table migrations

- apps/nextjs/src/components/AppComponents/Chat/ui/icons.tsx
- Linting - ensure readonly props for the icons
> fix: readonly props for icons.tsx

- apps/nextjs/src/components/AppComponents/Chat/chat-panel-disclaimer.tsx
- packages/db/scripts/import-export/validate_data.ts
- packages/exports/src/utils.ts
- Addresses some of the issues marked as "major" in our sonar report
> fix: address sonar major issues

- apps/nextjs/src/components/DialogControl/DialogContents.tsx
Fixes share and end of lesson dialogs by removing icons
> fix: icons in dialogs

- apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.tsx
- packages/aila/src/features/moderation/moderators/index.ts
- Fixes some Sonar issues marked as "maintain"
> fix: sonar maintain linting #2

- apps/nextjs/.eslintrc.cjs
- apps/nextjs/src/app/aila/[id]/download/DownloadView.tsx
- apps/nextjs/src/app/api/chat/fixtures/FixtureRecordLLMService.ts
- apps/nextjs/src/components/AppComponents/QuizDesigner/Hero.tsx
- apps/nextjs/src/components/AppComponents/QuizDesigner/SuggestedQuestionCard.tsx
- apps/nextjs/src/components/DialogControl/DialogContents.tsx
- packages/aila/src/core/chat/AilaChat.ts
- packages/aila/src/features/categorisation/categorisers/AilaCategorisation.ts
- packages/aila/src/features/categorisation/categorisers/MockCategoriser.ts
- packages/aila/src/features/generation/AilaGeneration.ts
- packages/aila/src/features/generation/index.test.ts
- packages/aila/src/features/moderation/AilaModeration.ts
- packages/aila/src/features/moderation/moderators/MockModerator.ts
- packages/aila/src/features/moderation/moderators/OpenAiModerator.ts
- packages/aila/src/features/moderation/moderators/index.ts
- packages/aila/src/features/persistence/adaptors/prisma/index.ts
- packages/aila/src/features/rag/AilaRag.ts
- packages/aila/src/features/snapshotStore/AilaSnapshotStore.ts
- packages/aila/src/features/threatDetection/AilaThreatDetection.ts
- packages/aila/src/features/threatDetection/detectors/MockThreatDetector.ts
- packages/core/src/models/lessonPlans.ts
- packages/core/src/models/lessonSummaries.ts
- packages/eslint-config-custom/index.js
- Addresses some sonar issues marked as "maintain"
- Promisifies some non-async methods
- Adds readonly properties to various classes that are not modifying them
> fix: sonar maintain linting #1

- apps/nextjs/src/ai-apps/quiz-designer/quizRequestGeneration.ts
- apps/nextjs/src/components/AppComponents/QuizDesigner/QuizQuestionRow/Question.tsx
- apps/nextjs/src/hooks/useRegenerateAnswers.ts
- apps/nextjs/src/hooks/useRegenerateDistractors.ts
- packages/logger/index.ts
- Addresses an issue where async methods in the quiz designer were not being properly handled, and Sonar was flagging it for intentionality
> fix: intentionality of async / promise code for question generation

- apps/nextjs/src/app/api/cron-jobs/expired-exports/route.ts
- apps/nextjs/src/app/api/cron-jobs/google-drive-size-quota/route.ts
- apps/nextjs/src/middlewares/auth.middleware.ts
- apps/nextjs/vercel.json
- packages/core/src/utils/slack.ts
- Adds new cron job that runs after expired exports and reports if storage is over 80% 
- Adjusts expired exports to delete files on while condition.
> feat: report google drive storage quota

- .vscode/extensions.json
- README.md
- apps/nextjs/src/ai-apps/lesson-planner/state/actions.ts
- apps/nextjs/src/app/api/chat/errorHandling.test.ts
- apps/nextjs/src/app/lesson-planner/preview/[slug]/page.tsx
- apps/nextjs/src/app/quiz-designer/preview/[slug]/page.tsx
- apps/nextjs/src/components/AppComponents/Chat/chat-left-hand-side.tsx
- apps/nextjs/src/components/AppComponents/Chat/chat-message/ChatMessagePart.stories.tsx
- apps/nextjs/src/components/AppComponents/Chat/chat-message/ChatMessagePart.tsx
- apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.tsx
- apps/nextjs/src/components/AppComponents/QuizDesigner/QuizQuestionRow/Distractor.tsx
- packages/aila/tsconfig.json
- packages/api/tsconfig.json
- packages/db/tsconfig.json
- packages/eslint-config/src/index.mjs
- packages/eslint-config/src/rules.mjs
- packages/eslint-config/tsconfig.json
- packages/exports/tsconfig.json
- packages/ingest/tsconfig.json
- Reinstates the rules of hooks eslint config
- Adds some documentation to the Readme about standards / linting / quality
- Fixes some small linting issues
> chore: reinstate react hooks linting, fix linting issues

- packages/core/src/inngest/index.ts
- packages/core/src/scripts/import-new-lessons/createSnippetsForNewLessons.ts
- packages/core/src/scripts/import-new-lessons/getTranscriptsForNewLessons.ts
- packages/core/src/scripts/import-new-lessons/importNewLessons.ts
- packages/core/src/scripts/processLessons.ts
- packages/core/src/scripts/seedLessons.ts
- packages/core/src/scripts/setupPrompts.ts
- packages/core/src/tracing/baseTracing.ts
- packages/db/scripts/processing/add_metadata_to_lesson_summaries.ts
- packages/db/scripts/processing/add_metadata_to_snippets.ts
- packages/logger/index.ts
- Replace console.log instances in core package
- Not user-facing
> chore: replace console.log in the core package

- packages/db/prisma/seed.ts
- Removes a complaint about unexpected console.log in the db/seed script
> chore: use logger in db seed script

- packages/db/client/index.ts
- Removes a linting issue around unused variables
- Derives the type of PrismaClientWithAccelerate using ReturnType
> chore: derive prisma type using ReturnType

- apps/nextjs/src/mocks/oakai/db.ts
- apps/nextjs/tests-e2e/tests/aila-chat/downloads.test.ts
- apps/nextjs/tests-e2e/tests/auth.test.ts
- packages/aila/src/features/analytics/adapters/PosthogAnalyticsAdapter.ts
- packages/aila/src/features/persistence/adaptors/file/index.ts
- packages/aila/src/features/persistence/adaptors/kv/index.ts
- packages/aila/src/features/rag/NullAilaRag.ts
- packages/aila/src/features/threatDetection/detectors/HeliconeThreatDetector.ts
- packages/aila/src/lib/openai/OpenAICompletionWithLogging.ts
- packages/api/src/router/generations.ts
- packages/eslint-config/src/index.mjs
- Fixes several small linting errors around async functions needing Promise.resolve
- Adds aiLogger in tests
- Fixes a few small issues around not awaiting promises
> chore: fix linting errors around await / logging

- packages/ingest/src/db-helpers/step.ts
- packages/ingest/src/import-lessons/importLessonsFromCSV.ts
- packages/ingest/src/steps/4-lp-chunking.ts
- Fix some issues with ingest around async functions not being expected, add logging
- Not user-facing
> chore: add error logging, remove async function in ingest script

- turbo.json
- adds elasti creds env names to turbo.json
> chore: add elastic creds to turbo.json

- .github/workflows/test.yml
- remove env from test.yml which was unecessary and didn't fix the issue
> chore: remove env from test.yml

- apps/nextjs/src/app/api/aila-download-all/route.ts
- Fixes issue in RC with hanging on download all
Fixes #
Complete download flow successfully
> chore: remove await from  archive finalize

- apps/nextjs/jest.config.mjs
- apps/nextjs/package.json
- apps/nextjs/src/stores/chatStore/__tests__/executeQueuedActions.test.tsx
- apps/nextjs/src/stores/chatStore/__tests__/handleAppend.test.ts
- apps/nextjs/src/stores/chatStore/__tests__/handleStop.test.ts
- apps/nextjs/src/stores/chatStore/__tests__/setMessages.test.ts
- apps/nextjs/src/stores/chatStore/index.ts
- pnpm-lock.yaml
- Test patterns for chat store
> test: chat store actions - AI-769

- apps/nextjs/src/components/AppComponents/Chat/chat-panel.tsx
- apps/nextjs/src/components/AppComponents/Chat/prompt-form.tsx
- apps/nextjs/src/stores/chatStore/index.ts
Just a small one to move the text input field to the chat store
> refactor: move input field to chat store

- apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
- Fixes flash in streaming lesson plan
> fix: lesson flash after moderation

- apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
A single fix to address flashing of the lesson panel in the earlier release.
> build: release candidate

- apps/nextjs/src/app/aila/[id]/page.tsx
- apps/nextjs/src/app/aila/[id]/share/index.tsx
- apps/nextjs/src/middlewares/auth.middleware.ts
- fixes:
https://www.notion.so/oaknationalacademy/FAQ-behind-auth-13e26cc4e1b1806cad23e86dac249fba
https://www.notion.so/oaknationalacademy/Share-page-link-14a26cc4e1b1807b976ddc21a0644563
https://www.notion.so/oaknationalacademy/Logout-from-lesson-error-14926cc4e1b180049478d2b3e1d03371
> chore: clerk snags

- apps/nextjs/src/components/AppComponents/Chat/user-or-login.tsx
- The annoying hydration error is no more!
> chore: fix hydration error on aila

- packages/core/src/utils/rateLimiting/userBasedRateLimiter.ts
Sometimes a user has a valid usage for some spiky usage which takes them over the rate limit, for example when preparing a batch of lessons to go on leave. This is an early version of allowing individual users to have higher limits in exceptional cases
- Check user metadata for `hasHigherLimits` when in UserBasedRateLimiter
Fixes #
- Exhaust a user's rate limit (ask someone with doppler access to drop `RATELIMIT_GENERATIONS_PER_24H` to a number like 5
- Set the **hasHigherLimits** to `true` in the user's privateMetadata in clerk
- The user shouldn't be rate limited
> feat: allow lifted rate limits for certain users

- .github/workflows/lint.yml
- .prettierignore
- package.json
- packages/prettier-config/index.mjs
- We seem to be using Prettier somewhat inconsistently and formatting issues have been slipping in
- This adds a Prettier check before merging PRs to ensure that code is formatted correctly
- No user-facing changes
If you get a Prettier linting failure it will look like this:
This PR itself is failing until the preceding PRs merge so we can see that it's working.
> feat: run Prettier before merging PRs

- apps/nextjs/src/components/Header.tsx
- apps/nextjs/src/components/TempBanner.tsx
> chore: remove temp banner

- apps/nextjs/src/components/Footer.tsx
horrible important tags, located much bigger issue re styled components
> chore: important tags

- packages/db/prisma/migrations/20250529100003_move_am_to_public_schema/migration.sql
- packages/db/prisma/schema.prisma
- deletes current am file and moves am to public schema where stg + prd db users can access to the table
> chore: am db to public table

- .vscode/settings.json
> chore: remove accidently added vs code custom colours

- apps/nextjs/src/components/AppComponents/AdditionalMaterials/ResourcesFooter.tsx
- apps/nextjs/src/components/AppComponents/AdditionalMaterials/StepLayouts/StepFour.tsx
- apps/nextjs/src/components/AppComponents/AdditionalMaterials/StepLayouts/StepThree.tsx
- apps/nextjs/src/components/AppComponents/AdditionalMaterials/StepLayouts/StepTwo.tsx
- apps/nextjs/src/components/ResourcesLayout.tsx
- apps/nextjs/src/stores/resourcesStore/actionFunctions/handleGenerateMaterial.ts
- apps/nextjs/src/stores/resourcesStore/actionFunctions/handleRefineMaterial.ts
- apps/nextjs/src/stores/resourcesStore/actionFunctions/handleUndoRefinement.ts
- apps/nextjs/src/stores/resourcesStore/index.ts
- apps/nextjs/src/stores/resourcesStore/selectors.ts
- apps/nextjs/src/stores/resourcesStore/types.ts
- packages/additional-materials/src/documents/additionalMaterials/dataHelpers/transformDataForExports.ts
> feat: am mobile implementation
