.vscode/settings.json

- Removes the colour overrides in the vscode settings so that developers can choose their own individual colour profile

fix: remove workspace colour overrides

---

packages/core/src/prompts/lesson-assistant/parts/americanToBritish.ts
packages/core/src/prompts/lesson-assistant/parts/basedOn.ts
packages/core/src/prompts/lesson-assistant/parts/body.ts
packages/core/src/prompts/lesson-assistant/parts/context.ts
packages/core/src/prompts/lesson-assistant/parts/endingTheInteraction.ts
packages/core/src/prompts/lesson-assistant/parts/generateResponse.ts
packages/core/src/prompts/lesson-assistant/parts/interactive.ts
packages/core/src/prompts/lesson-assistant/parts/rag.ts
packages/core/src/prompts/lesson-assistant/parts/schema.ts
packages/core/src/prompts/lesson-assistant/parts/signOff.ts
packages/core/src/prompts/lesson-assistant/parts/task.ts
packages/core/src/prompts/lesson-assistant/parts/yourInstructions.ts

- Update the prompt to:
- improve distractor length so that it is more consistent with answer length
- improve slide text for learning cycles
- improve practice task relevance, content and duration
- address grammar issues in the text
- standardise on double quotes
- standardise one sentence per line for easier diffs

feat: update prompt with distractor, practice task and grammar improvements

---

apps/nextjs/src/components/Feedback/index.tsx

- User could not see what they had selected in the feedback dialog at the end of a chat.
- Responses weren't mapping to correct columns in PostHog.
1. Go to a chat with a fresh browser and clear cookies
2. Ensure you have accepted cookies
3. Go to the download page and wait for the dialog to pop up 
4. Select an item
5. It should be obvious what is selected
6. On submitting the form, data should appear correctly in PostHog.

fix: user feedback on selection in the feedback dialog and mapping responses in posthog correctly

---

package.json
packages/aila/src/features/generation/AilaGeneration.ts
packages/core/src/models/promptVariants.ts
packages/core/src/prompts/lesson-assistant/parts/body.ts

- Fixes an issue where there could be only one current prompt for each slug, irrespective of the variant
- Ensures there is one current prompt for each variant
- Ideally, developers should use pnpm prompts:dev to set up their prompts initially, but it tries to create the prompt variant if it is not found

fix: prompt version hash

---

.github/workflows/playwright.yml
.github/workflows/post_deployment.yml

Two of our Github workflows are triggered by successful deployments, and then search for a PR with that SHA. They both fail if a branch is pushed before the PR is created
- Skip GH actions that rely on the PR number if it's missing

chore: skip Github workflows that depend on PR ID when PR doesn't exist

---

packages/core/src/prompts/lesson-assistant/parts/body.ts

Changes to MCQ examples and non-examples
- changed the example and non-example to be about the periodic table.

chore: update body to change MCQ examples and non-examples.ts

---

apps/nextjs/src/middlewares/auth.middleware.ts

We had an error where the users got into an onboarding redirect loop in the production environment only. This was because the production session claims in clerk weren't up to date with the template in staging
We previously made a hotfix to disable this behaviour. We can now enable it again
1. Deploy this PR to production (don't alias until known to be working)
2. Log in with an account missing `isDemoUser` metadata
3. You shouldn't be in a redirect loop

fix: re-enable onboarding redirect after clerk claim update

---

apps/nextjs/src/components/ContextProviders/GleapProvider.tsx

- Gleap only let us change the background colour in their UI. This PR overrides the Gleap styling subtly to make the black *our* black, and the sans serif *our* sans serif
I know it's not a great practice to do this, but if they do change class names the consequences will be very minimal: A different black and different font
How it used to look

feat: override styles for gleap button

---

apps/nextjs/src/app/home-page.tsx
apps/nextjs/src/components/AppComponents/Chat/beta-tag.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-history.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-start.tsx
apps/nextjs/src/components/AppComponents/Chat/header.tsx
apps/nextjs/src/components/AppComponents/Chat/sidebar-mobile.tsx
apps/nextjs/src/components/AppComponents/Chat/ui/icons.tsx
apps/nextjs/src/components/AppComponents/Chat/ui/sheet.tsx
apps/nextjs/src/components/AppComponents/Chat/user-or-login.tsx

- Use "Aila" in headers
- Use acorn logo
- Tighten spacing of Beta label
- Hide help on mobile header
- Move menu to right and add text label on desktop
- Adjust icon sizes in header
- Make sidebar slide out from right
- Shrink icon sizes in sidebar
- Shrink sidebar X button and bring content below a bit closer
https://www.figma.com/design/8yhBj0ewAVelXOPEKEvCNu/Mobile-view-tests?node-id=2427-5649&node-type=SECTION&t=uMfCMo3HRoQh0CQT-0
1. Go to https://oak-ai-lesson-assistant-3ie0o7hoz.vercel-preview.thenational.academy/aila
2. Look at the nav and the menu
3. Look again at a mobile width

feat: bring nav in line with mobile design

---

apps/nextjs/src/components/MainNavigation/MainNavigationMenu.tsx
apps/nextjs/src/components/MainNavigation/MobileListItem.tsx
apps/nextjs/src/data/menus.tsx

- Adds a link to the Oak blogs for AI
- Adds spacing to "Back to Oak" icon
1. Go to https://oak-ai-lesson-assistant-8b2s70h2x.vercel-preview.thenational.academy
2. Click on the menu
3. You should see the link
4. Click on the link
5. You should in on the oak blog, with the AI category (currently there aren't any published posts)

feat: add homepage link to AI blogs

---

apps/nextjs/src/app/aila/[id]/download/DownloadView.tsx

- Add text to explain why you can't download if you don't have 10/10 sections complete
- Update "Lesson" section to "Lesson plan"
1. Go to https://oak-ai-lesson-assistant-pwh6d95ed.vercel-preview.thenational.academy
2. Create a new lesson
3. Click on "download"
4. You should see the friendly explanation

feat: help text when downloading an unfinished lesson

---

packages/aila/src/protocol/jsonPatchProtocol.ts

- Adds 'patch json schema' to 'llm response json schema'
- This should make it likely to follow the format a little close, as it's a more formal explanation of the patch protocol than is written later in the prompt

fix: include patch schema in llm response schema

---

apps/nextjs/src/components/AppComponents/Chat/chat-start.tsx

fix: remove duplicate beta tag on mobile

---

apps/nextjs/src/middlewares/csp.ts

We shouldn't be using this domain ourselves, but something in our project is trying to load IBM Plex. It could be a third party for example. We can trust Google Fonts, so I think we should just enable it
This has triggered 1.8k times
https://oak-national-academy.sentry.io/issues/425476

chore: add fonts.static.com to font csp

---

packages/core/src/utils/ailaModeration/helpers.ts

Sometimes the moderation prompt returns all categories for a benign "sensitive" input. Until we can address the root cause, detect this case

fix: downgrade moderation if all categories triggered at same time

---

packages/core/src/prompts/lesson-assistant/variants.ts

- Currently the variants for the Aila prompt are created inline whenever the variants.ts file is imported
- This shifts it into a method that is called in the prompt initialisation script instead

fix: ensure prompt variants are initialised correctly

---

apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
apps/nextjs/src/components/ContextProviders/Demo.tsx

The download and share bar were dropped by the demo account banner for users on demo accounts.
Fixes #
1. Go to a chat in development on mobile
2. You should be able to access the share and download buttons

fix: mobile downloads blocked on demo

---

apps/nextjs/src/components/ContextProviders/AnalyticsProvider.tsx
packages/aila/src/features/moderation/moderators/OpenAiModerator.ts
packages/core/src/utils/ailaModeration/helpers.ts
packages/core/src/utils/ailaModeration/moderationCategories.json
packages/core/src/utils/ailaModeration/moderationSchema.ts

As per #79, sometimes the moderation LLM call returns all possible moderation categories for an input. This incorrectly flags a toxic status which locks the lesson, etc
This is an approach to detect this case using a `t/dummy-smoke-test` category

fix: add dummy moderation category to detect over-eager moderation

---

apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx

Fixes #
1. Go to https://oak-ai-lesson-assistant-huczl8uwl.vercel-preview.thenational.academy
{screenshots}
{screenshots}

fix: remove demo header margin on mobile

---

apps/nextjs/src/app/home-page.tsx

- Made the video container 100% so that flexbox doesn't shrink it so much on a smaller viewport
- Updated the thumbnail of the2nd video
{screenshots}
{screenshots}

fix: fix homepage video reponsive layout

---

packages/aila/src/features/moderation/moderators/OpenAiModerator.ts

- removes 'input' from logs, which often was meaning that there wasn't space in the log for the moderationResult (it was cut off)
- we can look up input in the moderations table if we want, but we don't store the full moderation response, so the log is useful in itself

chore: ensure whole moderation result is logged

---

.github/workflows/accept_release_candidate.yml

We release by creating a release candidate PR and then merging it. We need to merge it with the "merge" strategy. For our own PRs, we should use the "squash" strategy. Github remembers your last-used strategy so it's easy to get this wrong
This automation will automatically merge the RC to production when someone approves it

chore: add workflow to merge approved RCs

---

apps/nextjs/package.json
packages/aila/package.json
packages/aila/src/constants.ts
packages/aila/src/features/moderation/moderators/OpenAiModerator.ts
packages/core/package.json
packages/core/src/utils/ailaModeration/moderationCategories.json
packages/core/src/utils/ailaModeration/moderationPrompt.ts
packages/core/src/utils/ailaModeration/moderationSchema.ts
packages/db/package.json
pnpm-lock.yaml

I tried a few variants locally (prompt/model combinations), and this was the best I found. (note: gpt-4o-mini is no good for this!).
- updates open-ai from 4.52.0 to 4.58.1 (allowing for json_schema mode) 
- moderation agent now uses "json_schema" mode
- adds a 'note' to the Toxic moderation category description
- amends 'instruction' setting of the prompt
- makes justification non-optional
- filter categories by parent category score
Later will explore some more in-depth changes, but that would come with more risk associated, so want to do that when there's a dataset (and more time) to give the confidence required.
https://www.notion.so/oaknationalacademy/Fix-moderation-bug-where-all-categories-get-flagged-3c93a1e819bb438f971187cb8be653bc
1. Moderation should generally work (e.g. test …

fix(moderation prompt): lower false positives in toxic category

---

apps/nextjs/src/app/home-page.tsx

fixes: https://www.notion.so/oaknationalacademy/Mobile-video-sizing-aad5baea2dd14bfb856506ed194419d6

fix: mobile video sizing

---

apps/nextjs/src/app/api/chat/chatHandler.ts
apps/nextjs/src/app/api/chat/config.ts
apps/nextjs/src/app/api/chat/errorHandling.test.ts
apps/nextjs/src/app/api/chat/errorHandling.ts
apps/nextjs/src/app/api/chat/route.test.ts
apps/nextjs/src/app/api/chat/user.test.ts
apps/nextjs/src/app/api/chat/user.ts
apps/nextjs/src/app/api/chat/webActionsPlugin.test.ts
packages/aila/src/core/chat/AilaStreamHandler.ts
packages/aila/src/features/threatDetection/types.ts
packages/aila/src/utils/moderation/moderationErrorHandling.ts
packages/core/src/utils/rateLimiting/userBasedRateLimiter.ts

Our streaming chat protocol allows us to send predefined error and action messages when a user is banned, rate limited, etc. With recent refactors we've lost some of that functionality
Changes:
- Replace `failureMessage` pattern in chat handler, and throw specific error instances instead
- Extract error handling code to new file
- Catch known error instances in chat handler, and respond with the appropriate protocol message
- Remove redundant wrappers around user lookup function
- Remove  `shouldPerformUserLookup`, `handleUserLookup`, `mockUserId` functionality as it was only used to support tests
Rate limiting
1. Set a low `RATELIMIT_GENERATIONS_PER_24H` in doppler
2. Rebuild the deployment
3. Go to https://oak-ai-lesson-assistant-6qy6b39gj.vercel-preview.thenational.academy
4. Sign in …

fix: return protocol error messages for user restrictions

---

apps/nextjs/src/app/manifest.ts
package.json

- Adds web app manifest for [next app](https://nextjs.org/docs/app/building-your-application/configuring/progressive-web-apps#1-creating-the-web-app-manifest).
- Might need to tweak the config, but it currently displays as below.
Fixes [#AI-510](https://www.notion.so/oaknationalacademy/Add-PWA-manifest-fafdd33db57541fb879df03a4d133cba?pvs=4).
1. Go to https://oak-ai-lesson-assistant-np4cw1eeb.vercel-preview.thenational.academy on Chrome.
2. Install web app.
3. You should see the installed web app in Chrome Applications.

feat: add pwa manifest

---

apps/nextjs/src/components/AppComponents/Chat/chat-message/index.tsx

Type 'user' was overriding background colour of the chat message box for `generic` and `moderation ` error messages on reload of the page.
- Change order of classes so errorType has precedence.
https://www.notion.so/oaknationalacademy/Sensitive-warnings-lose-colour-d1b3361edcf7478ea3b04f7be844a7ce
1. Go to https://oak-ai-lesson-assistant-p6i18zgf9.vercel-preview.thenational.academy
Create a lesson with sensitive content, refresh the page, sensitive content box remains mint green colour

fix: error colour precedence in message wrapper

---

apps/nextjs/src/components/AppComponents/QuizDesigner/Hero.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/QuizContent.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/QuizDesignerPageContent.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/QuizQuestionRow/index.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/SubjectKeyStageSection/Choose.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/SubjectKeyStageSection/index.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/SuggestedQuestionCard.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/SuggestedQuestions.tsx
apps/nextjs/src/hooks/useSuggestedQuestions.ts

Fixes issus in:
https://www.notion.so/oaknationalacademy/Quiz-Designer-Issues-e94d079850f349709023b751fe31bae2

fix: quiz designer snags

---

packages/aila/src/protocol/schema.ts

- this adds an enum for key stages
- it unions with `z.string()` just in case, although we might decide to lose that down the line

fix: prompt key stage enum

---

packages/core/src/rag/index.ts

- we're looking in the wrong table at one point, would've been causing an issue when LLM returned a KS which wasn't a simple match for one in our db, looks like it affects RAG

fix: fuzzy key stage from correct table

---

apps/nextjs/src/app/api/chat/errorHandling.test.ts
apps/nextjs/src/app/api/chat/protocol.ts
apps/nextjs/src/utils/testHelpers/consumeStream.ts

- reverts https://github.com/oaknational/oak-ai-lesson-assistant/pull/122
- fixes [issue described in this slack thread](https://oaknationalacademy.slack.com/archives/C05RYE3JL4S/p1726559097143399)

fix: revert error to previous protocol

---

apps/nextjs/src/middleware.ts

- currently PR'd as a hotfix to production
- attempt to get fewer of these errors https://oak-national-academy.sentry.io/issues/214659/?project=4507089597300816
- code copied from [NextResponse docs](https://nextjs.org/docs/app/api-reference/functions/next-response#json)
- hard to know if this is the issue, as there are few details in the Sentry event. But this is the only place we call `.error()` on a response object
- also, for this code to have been running, there would have been an error in this code:
```ts
response = await authMiddleware(request, event);
response = addCspHeaders(response, request);
```

fix: use NextResponse.json() in case of middleware errors

---

packages/api/src/router/chatFeedback.ts

- instantiate Error with `{ cause }` rather than setting as property on instance. Seems to be better picked up by Sentry

chore: instantiate errors with cause

---

apps/nextjs/src/middlewares/auth.middleware.ts

Our middleware-related sentry errors don't give us much context:
`Error in nextMiddleware`
=> `Unexpected token [redacted]... is not valid JSON`
I'm hoping that wrapping the different places that might throw an error might help to narrow down the origin of the errors

chore: wrap auth middleware errors

---

apps/nextjs/src/components/AppComponents/Chat/chat-layout.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-left-hand-side.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-lhs-header.tsx
apps/nextjs/src/components/AppComponents/Chat/prompt-form.tsx
apps/nextjs/src/components/DownloadButton.tsx
packages/aila/src/protocol/sectionToMarkdown.ts
packages/exports/src/exportDocsWorksheet.ts

https://www.notion.so/oaknationalacademy/Mobile-banner-on-demo-accounts-covering-download-button-b8ac439a24a4464b8f45687450ad4bdf
https://www.notion.so/oaknationalacademy/Remove-timings-from-Learning-cycles-040292e0d72748ecaa67b5b741760490
https://www.notion.so/oaknationalacademy/Aila-chat-input-box-expansion-10626cc4e1b1801fb09ffa05fb607756
https://www.notion.so/oaknationalacademy/Feedback-Form-Sizing-10426cc4e1b18022addddbdf27ec49f9

fix: small bugs

---

apps/nextjs/src/components/DialogControl/ContentOptions/ShareChatDialog.tsx

The share page was being blocked on safari as it blocks windows from being opened async as pop-ups. 
This separates out the experience so the user creates the page and then has a user action to go to the page, allowing for errors to be fed back to the user.

fix: safari blocking share page as it was an async window pop up

---

apps/nextjs/src/components/AppComponents/Chat/chat-panel.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-quick-buttons.tsx
apps/nextjs/src/components/AppComponents/Chat/prompt-form.tsx
apps/nextjs/src/components/ContextProviders/ChatProvider.tsx

- Adjusts the in-moderation interaction feature so that both the quick buttons component and the prompt form are managed by the ChatProvider
- Ensures matching logic between all related components about when they can be interacted with
- Start a chat
- During the moderation step when the left hand message first appears, click Continue.
- Notice you can't type in the box or click Continue again
- Do the same by typing in the box
- Wait until it is interactive again
- Type in the box again
- Notice the placeholder is the text you typed (it's queued)
- Notice it submits after a few seconds

fix: stop interaction except in moderation or idle

---

apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
apps/nextjs/src/hooks/useTemporaryLessonPlanWithStreamingEdits.ts

- Addresses an issue where the chat is blank when navigating back from the downloads page
1. Create a complete chat
2. Go to the download page
3. Press the back to lesson link at the top left
4. See that the chat has loaded

fix: refetch chat on mount to fix the blank chat issue on back navigation

---

vercel-ignore-build.sh

- Adds a script to use [Vercel's ignored build step](https://vercel.com/docs/projects/overview#ignored-build-step) to stop the merge commit on `production` trying to build and deploy.
1. The preview build for this branch should work.
2. On the production branch, the merge commit should not be built.

ci: add vercel ignore build script to ignore production merge commits

---

apps/nextjs/package.json
pnpm-lock.yaml

Update playwright to [v1.47](https://playwright.dev/docs/release-notes#version-147)
We're mainly updating for the new "show route actions" setting, which significantly tidies up the UI mode for us

chore: update playwright

---

apps/nextjs/src/app/aila/[id]/download/DownloadView.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/index.tsx

A recent change to the download page broke the test IDs used in our e2e test. One was missing, and the other was duplicated

test: fix download test IDs

---

apps/nextjs/src/components/AppComponents/Chat/chat-quick-buttons.tsx
apps/nextjs/src/components/ContextProviders/ChatProvider.tsx

Our end-to-end tests look at the existence of the "stop" button to determine when the chat is streaming. This started failing in a test where it submitted a message while the chat was moderating
It actually highlights an issue with our new "queueing during moderation" UI
On main/production:
- When you queued a message in the chat, the stop button wouldn't appear until the queued message was sent and started streaming
With this branch:
- When you queue a message, you can click "stop" to unqueue it. This replicates the UI for a non-queued message

fix: enable stop button to clear queuedAction

---

apps/nextjs/playwright.config.ts

End to end tests can be flaky. While the ideal is to not have flaky tests, the reality is that failing tests on PRs lead developers to expect or ignore a failing check
This PR allows a retry in CI in case a failure is just flake

test: allow one e2e retry in CI

---

apps/nextjs/src/components/AppComponents/download/DownloadAllButton.tsx
apps/nextjs/src/components/ExportsDialogs/useExportAdditionalMaterials.ts
apps/nextjs/src/components/ExportsDialogs/useExportAllLessonAssets.ts
apps/nextjs/src/components/ExportsDialogs/useExportLessonSlides.ts
apps/nextjs/src/components/ExportsDialogs/useExportQuizDesignerSlides.ts
apps/nextjs/src/utils/useClientSideFeatureFlag.ts

The "download all" button is blocking our latest release. Rather than try to fix it further on main, let's disable it and fix it out-of-band
The feature hook wasn't being used, so it seems like a good opportunity to simplify it. Our analytics setup has changed and I don't think that we need to identify here any more
The features has been created in posthog staging and production

fix: feature flag "download all" button

---

packages/db/prisma/migrations/20241002105843_snippets_fts_index/migration.sql

- Adds a full-text search index to the snippets table that we had on the old production DB.
- @remy was reporting performance hits using the new DBs, we identified this as the probable culprit.
- The snippets table we're applying this too is pretty hefty, but as we're not writing to it it shouldn't be an issue.
Fixes #ENG-985
1. Once applied to production, test the transcripts API route on the Open API.

perf: add fts index to snippets table

---

README.md
apps/nextjs/playwright.config.ts
apps/nextjs/tests-e2e/config/common-auth.setup.ts
apps/nextjs/tests-e2e/tests/aila-chat/auth.test.ts
apps/nextjs/tests-e2e/tests/aila-chat/downloads.test.ts
apps/nextjs/tests-e2e/tests/aila-chat/flexible-prompt-live.test.ts
apps/nextjs/tests-e2e/tests/aila-chat/full-romans.test.ts
apps/nextjs/tests-e2e/tests/aila-chat/helpers.ts
apps/nextjs/tests-e2e/tests/auth.test.ts
apps/nextjs/tests-e2e/tests/quiz-designer.test.ts

Our older e2e tests sign in by manually typing test credentials into the sign in form. We have a new approach which generates test users and signed them in through the clerk API. This PR brings those older tests in line with our new approach
- Keep the existing `@authenticated` setup step, but rename it to `@common-auth` as other tests can still authenticate individually
- Call `prepareUser` from the common auth setup step
- Save the chatId from prepareUser to a cookie, so individual tests can retrieve it and test against a completed chat
- Create a new auth.test.ts test file which goes through a clerk login manually
- Remove unnecessary `test.describe` wrappers as they add noise the test UI
- Set maximum concurrent workers to 5 in development. I found testing this that pressing the big …

test: add @common-auth strategy to e2e tests

---

packages/aila/src/protocol/schema.ts

**So that the ingest service PR isn't too unwieldy, I'm trying to break it into smaller PRs**
- This one updates the CompletedLessonPlan schema  so that it doesn't use Zod min() and max(), which aren't supported by Structured Output

chore: update CompletedLessonPlanSchema so doesn't use min() or max()

---

apps/nextjs/src/middleware.ts

At the moment, parsing errors are triggering exceptions which get reported to Sentry. We should be able to assume that any SyntaxError is not an exception and can be handled with a 400 response

fix: return a 400 for invalid input to middleware

---

.github/workflows/playwright.yml

When testing #186 I found that just installing chromium saves us 30 seconds or so in playwright build time. We may as well take that benefit from that (closed) PR

build: install specific playwright browsers

---

docs/diagrams/chat-sequence.md

- Updates chat sequence diagram to better represent the chat flow with it's constitute parts.
Fixes [#576](https://www.notion.so/oaknationalacademy/Update-chat-sequence-diagram-11826cc4e1b180768798d297971b00c1?pvs=4)
1. Go to the folder on the branch on Github: https://github.com/oaknational/oak-ai-lesson-assistant/blob/AI-576-chat-sequence-diagram/docs/diagrams/chat-sequence.md
2. The new sequence diagram should show and be correct.

docs: update sequence diagram

---

apps/nextjs/src/app/api/aila-download-all/route.ts
apps/nextjs/src/app/api/aila-download/route.ts
apps/nextjs/src/app/api/sanitizeFilename.test.ts
apps/nextjs/src/app/api/sanitizeFilename.ts

- Strip out url and filename unfriendly characters from content disposition header when downloading
- Should fix https://oak-national-academy.sentry.io/issues/6482803
- Potentially fixes https://oaknationalacademy.slack.com/archives/C05RYE3JL4S/p1727855976518189

fix: sanitize file names before downloading

---

apps/nextjs/playwright.config.ts

A small change! It's pretty hard to understand a playwright failure without a screenshot or report. This will pop up the interactive report in development if a test fails. Only when running `test-e2e`, not `test-e2e-ui`

test: use html reporter and show popup on failure

---

packages/db/prisma/migrations/20241003170656_ingest_schema/migration.sql
packages/db/prisma/schema.prisma
packages/ingest/src/db-helpers/createCaptionsRecord.ts
packages/ingest/src/db-helpers/createErrorRecord.ts
packages/ingest/src/db-helpers/getLatestIngestId.ts
packages/ingest/src/db-helpers/getLessonsByState.ts
packages/ingest/src/db-helpers/step.ts
packages/ingest/src/db-helpers/updateLessonsState.ts

- updates to `prisma.schema` including
- adding 'multiSchema' with schema 'ingest' in addition to the default 'public'
- adding all the required tables to the 'ingest' schema 
- migration file for above changes
- adds 'db-helpers' directory as a with various database helper functions

chore: add ingest db-helpers

---

apps/nextjs/tests-e2e/tests/aila-chat/full-romans.test.ts

Our end-to-end test for the aila chat with fixtures is regularly failing. It got worse after removing an arbitrary delay before clicking the continue button
Problem:
- The e2e tests do some things quicker than a typical user, for example the moderation step is a lot quicker. This could cause race conditions which we don't normally see
- This doesn't mean that there isn't a bug, it could just be a rare one
- We want tests to be snappy, but also not spend too much time optimising our code for them
Solution:
- Use a small delay before clicking the continue button
- If we know that the test run is a retry, assume that the error could have been this race condition and increase the delay before clicking continue
I think we could also look for a different element to indicate that the response is …

test: add a delay after generation to let romans test settle

---

apps/nextjs/src/app/api/chat/errorHandling.test.ts
apps/nextjs/src/app/api/chat/protocol.ts
apps/nextjs/src/utils/testHelpers/consumeStream.ts

This reverts commit e053b895503d5a29522404ce14e13239b6db7852.
We reverted the protocol changes for error messages like the friendly rate limit message in the Chat. Now that we're using the latest protocol with structured outputs, we need the new version again

fix: revert "fix: revert error to previous protocol (#139)

---

apps/nextjs/tests-e2e/tests/auth.test.ts

When we had clerk issues, we deleted a number of accounts in the development environment. One of those was the account used for this test. Until we reinstate it or make the test more useful, we can skip it and get green test runs in our PRs

test: skip auth test failing from missing test@ account

---

apps/nextjs/src/lib/hooks/use-enter-submit.tsx

- Fixes an issue where requestSubmit is not available for form submission
- requestSubmit is not available in all JS runtimes and is not polyfilled
Fixes [Sentry issue 6204624](https://oak-national-academy.sentry.io/issues/6204624)

fix: add fallback if requestSubmit is not available

---

apps/nextjs/src/components/AppComponents/Chat/chat-message/index.tsx

- We have a very chatty error on Sentry due to the "unknown" part type. 15k requests per 30 days. This silences these errors since the "unknown" occurs during streaming and part validation before a type is detected.
Fixes [Sentry 3220470](https://oak-national-academy.sentry.io/share/issue/52bd3813ca0e4b8aa404fcc034b83fc6/)

fix: silence unknown part type errors

---

packages/core/src/utils/camelCaseToSentenceCase.ts

- Fixes an issue where we are using a lookbehind in the regex for camelcase conversion
- This is not supported in all JS runtimes and is not polyfilled
Fixes [Sentry issue 8821397](https://oak-national-academy.sentry.io/issues/8821397)

fix: remove lookbehind in regex for camelcase conversion

---

apps/nextjs/src/components/Onboarding/LegacyUpgradeNotice.tsx

This page isn't seen often and didn't get updated for mobile
Before:
After:

fix: spacing on onboarding upgrade screen [AI-500]

---

.github/workflows/playwright.yml

- Playwright results are viewable in an interactive report. You can see an overview of the run, and the detailed replay of each test including steps, assertions, failures, JS console, network, etc
- This report is static HTML and only works properly when served over HTTP(S)
- We've looked at various ways to host these alongside our test runs, and it looks like just pushing to vercel is the simplest approach. We already have user access etc set up there

build: deploy playwright reports to Vercel

---

packages/aila/src/protocol/schema.ts
packages/db/prisma/migrations/20241016122132_remove_chat_sharepath/migration.sql

- adds a migration to remove `sharePath` from app_sessions.output
- removes sharePath from associated schema/types

chore: remove chat `sharePath`

---

apps/nextjs/src/components/AppComponents/Chat/chat-lhs-header.tsx
apps/nextjs/tests-e2e/tests/aila-chat/helpers.ts
apps/nextjs/tests-e2e/tests/banned-users.test.ts

In #247 @stefl introduced a useful element on screen to show the streaming state. We can use this for more reliable e2e testing
This PR just adds that early and updates the test helpers

test: check streaming status directly

---

packages/api/src/router/testSupport/prepareUser.ts

Clerk has a 500 user limit in development, and test accounts are starting to fill it up
This PR updates the test user logic so that we delete the oldest test user whenever we have to create a new one. If for some reason an old PR is hanging around and its test users were deleted, it will silently recreate anyway
Example test emails include:
`test+......@thenational.academy`
`010203@thenational.academy`
`jimmy+02013@thenational.academy`
Old test users are determined based on the last sign in date

test: delete the oldest test user when creating a new one

---

.eslintrc.cjs
apps/nextjs/src/env/client.mjs
apps/nextjs/src/env/server.mjs
apps/nextjs/src/utils/useClientSideFeatureFlag.ts
packages/logger/.eslintrc.cjs

Now that we have a centralised logger #244, it will be useful to have a reminder about using the right log
@stefl I know you're hard at work on your PR, and I don't mind updating this PR after that's merged to avoid a conflict

chore: add no-console to eslint

---

packages/core/src/prompts/lesson-assistant/parts/interactingWithTheUser.ts
packages/core/src/prompts/lesson-assistant/parts/lessonComplete.ts

`lessonReferences` isn't in the schema, so this removes it from the prompt.
See this from an example bug it has caused:
```json
{
"type": "patch",
"reasoning": "Including the relevant lesson plan IDs to provide context for the user.",
"value": {
"type": "string-array",
"op": "add",
"path": "/learningCycles",
"value": [
"F63JsTLhsw-dKUs1yPf9m",
"r1F76TUL4kA2glhwMQD08",
"oanlozx7p8fLgQHSPHEkf",
"dibWRSkTYzld4sxuJF-kD",
"7kytsvMjNGEdlVTPrW16H"
]
}
}
```

fix: remove lessonReferences from prompt

---

packages/aila/src/core/chat/AilaStreamHandler.ts

My local e2e test for banned users has been broken. After lots of divide-and-conquer console.logs, I found that the cause was a problem connecting to my local inngest when handling a toxic moderation. As soon the code made that call, the following lines weren't executing
It turns out that errors thrown in `chat.complete` are being swallowed. This PR makes sure they get logged, and that they're reported to Sentry
Check out main, and throw an error in [AilaChat.complete](https://github.com/oaknational/oak-ai-lesson-assistant/blob/c4d85cc46c914c452947f62ee253d9ee5a025e71/packages/aila/src/core/chat/AilaChat.ts#L356). You should see that it stops the completion and doesn't report an error
Try the same on this branch and see an error in the log

fix: report chat completion errors

---

apps/nextjs/src/app/api/chat/route.ts

- Adds a GET route to /chat for the purposes of warming it up in local dev

fix: reinstate prebuilding the chat route in local dev

---

.gitattributes

- In PRs we see all of the generated fixtures and recordings we use in tests
- This adds a .gitattributes file which sets their status as generated
- Doing so automatically puts them into a hidden state in the PR
- You can still review them in the PR, but by default it shows them in a closed state with a notice that they are generated
- We could add other files to this as we go

chore: hide generated fixtures and recordings in PRs

---

packages/aila/src/core/chat/AilaChat.ts

- We have an occasional error where if the connection to /chat is terminated, the server will 500 because the enqueuer or the AilaChat instance itself goes away
- This has a check before enqueuing a message that the enqueuer still exists

fix: ensure that the patch enqueuer exists when enqueuing

---

apps/nextjs/src/lib/lessonPlan/sectionsInOrder.ts
packages/core/src/prompts/lesson-assistant/index.ts
packages/core/src/prompts/lesson-assistant/parts/body.ts
packages/core/src/prompts/lesson-assistant/parts/endingTheInteraction.ts
packages/core/src/prompts/lesson-assistant/parts/interactingWithTheUser.ts
packages/core/src/prompts/lesson-assistant/parts/lessonComplete.ts
packages/core/src/prompts/lesson-assistant/parts/promptingTheUser.ts
packages/core/src/prompts/lesson-assistant/parts/rag.ts
packages/core/src/prompts/lesson-assistant/parts/task.ts

We've had several issues to do with the prompt that this address:
- Automatically picking a lesson for basedOn
- Not completing all sections in a section group
- Doing a whole interaction when picking a basedOn rather than starting the lesson once the choice has been made
- Incorrectly using basedOn logic when there is no content
- Not having any guidelines for some sections
- Language being too lengthy
- Responses not relating to the actually-generated sections
This addresses several of these issues and fixes a bug whereby the with-RAG workflow was kicking in even though there were no relevant lessons.
Includes HB's recent prompt changes for the missing sections and updates the body with her PR.

feat: hint Aila as to which part of the lesson to update next

---

packages/db/package.json

- Sets the Postgres port to 8432 instead of the default 5432 in local development
- This means you can have Postgres running on your machine without a clash with the Oak Docker instance
If/when we merge this we will need to update the DB connection string in Doppler and rerun `pnpm docker-reset` in the db package.

chore: run the local Postgres DB on a non-default Postgres port

---

apps/nextjs/src/middleware.test.ts
apps/nextjs/src/middleware.ts
apps/nextjs/src/middlewares/__snapshots__/csp.test.ts.snap
apps/nextjs/src/middlewares/csp.test.ts
apps/nextjs/src/middlewares/csp.ts

- Alters the CSP header generation to support Turbo by using UUID instead of the crypto library (it has trouble with it)
- Adds a stricter definition of the environment name to save us getting mixed up between "prd" and "production"
- Fixes a bug that I think is in production right now
- Adds support for skipping the frame rules so that mobile tests run in dev

chore: csp support for turbo and add environment type

---

packages/logger/index.ts

I was looking at a frontend error in Sentry, and I spotted that this was logged:
> Invalid use of @oakai/logger, use logger/browser, logMessage=Oak consent client error
That makes sense as we globally replaced `console.error` commands with the central structuredLogger
This PR makes `aiLogger().error` choose between a server and browser logger as required

fix: use browserLogger for errors in the browser

---

packages/core/src/client.ts

Our inngest client skips dev mode if running in a jest test. I think this must be a typo. If you break an inngest mock, it will send to the inngest cloud

test: prevent jest from bypassing inngest dev mode

---

.github/workflows/test.yml

We updated the `test` script in package.json, but it turns out that the github workflow for testing calls turbo directly
This brings individual test file times down from ~40s to ~5s, as we don't have 3 jest processes each using the maximum available cores

test: reduce workers for jest in CI

---

.github/workflows/test.yml
package.json

- We should use the --noengine option for Prisma client generation in CI

fix: use noengine in ci

---

.vscode/settings.json

- Sets `"typescript.preferences.preferTypeOnlyAutoImports": true` so that VS Code will prefer to use type-only imports

fix: set VS Code to prefer type imports

---

apps/nextjs/.storybook/main.ts
apps/nextjs/jest.setup.js
apps/nextjs/next.config.js
packages/logger/index.ts

The `DEBUG` env var has helped me to keep local server logs clear and help me focus on specific areas I'm working on. At the moment that variable isn't configured on the frontend
This PR forwards the value in `DEBUG` to the frontend as well so we can filter logs there

chore: use DEBUG logging var on the frontend

---

apps/nextjs/src/app/aila/[id]/layout.tsx
apps/nextjs/src/app/aila/help/page.tsx
apps/nextjs/src/app/aila/page.tsx
apps/nextjs/src/app/faqs/page.tsx
apps/nextjs/src/app/generations/page.tsx
apps/nextjs/src/app/legal/account-locked/page.tsx
apps/nextjs/src/app/lesson-planner/page.tsx
apps/nextjs/src/app/lesson-planner/preview/page.tsx
apps/nextjs/src/app/quiz-designer/page.tsx
apps/nextjs/src/app/quiz-designer/preview/page.tsx
apps/nextjs/src/app/test-support/clerk/page.tsx

- Removes the "async" from Next.js pages which do not need it

fix: pages that do not load data do not need to be async

---

apps/nextjs/src/app/api/chat/route.ts

- The GET handler for the /chat API route needs to be promisified

fix: promisify chat API route get handler

---

turbo.json

```
@oakai/core:prompts: prisma:error 
@oakai/core:prompts: Invalid `this.prisma.prompt.create()` invocation in
@oakai/core:prompts: /vercel/path0/packages/core/src/models/promptVariants.ts:57:46
@oakai/core:prompts: 
@oakai/core:prompts:   54 >`SELECT MAX(version) AS max_version FROM prompts WHERE slug = ${slug}`;
@oakai/core:prompts:   55 const maxVersion = maxVersionRow[0]?.max_version ?? 0;
@oakai/core:prompts:   56 const version = maxVersion + 1;
@oakai/core:prompts: → 57 const created = await this.prisma.prompt.create(
@oakai/core:prompts: Unique constraint failed on the fields: (`hash`)
@oakai/core:prompts: PrismaClientKnownRequestError: 
@oakai/core:prompts: Invalid `this.prisma.prompt.create()` invocation in
@oakai/core:prompts: …
```

build: temporarily disable the prompts dependency when building RCs

---

apps/nextjs/tests-e2e/config/config.ts

- In local development we might want to have a different server other than the default (eg. if we want to run a server not in development mode, or using a different database)

feat: allow us to configure the server port for local testing

---

packages/api/src/router/exports.ts
packages/core/src/utils/sendEmail.ts
packages/core/src/utils/sendEmailRequestingMoreGenerations.ts
packages/core/src/utils/sendJudgementFeedbackEmail.ts
packages/core/src/utils/sendQuizFeedbackEmail.ts
packages/core/src/utils/stripHtml.ts

- changes the name of the email receipt to oak national academy
- changes teh email from being a pre tag to html

feat: update emails to use html

---

apps/nextjs/src/instrumentation.ts

We get errors like this when HMR kicks in with turbopack
It's tricky to debug. You seem to have to restart the server to reset the state that can break
```
Error: Module [project]/node_modules/next/dist/esm/client/components/error-boundary.js [app-ssr] (ecmascript) was instantiated because it was required from module [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { COMPONENT_0 => "[project]/apps/nextjs/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", COMPONENT_1 => "[project]/apps/nextjs/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js server component)", COMPONENT_2 => "[project]/apps/nextjs/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)", METADATA_3 => "[project]/apps/nextjs/src/app/twitter-image.png.mjs { IMAGE => …
```

fix: skip instrumentation when running turbopack - fix HMR

---

apps/nextjs/src/lib/feature-flags/bootstrap.ts
apps/nextjs/src/middlewares/auth.middleware.ts
packages/core/src/analytics/posthogAiBetaServerClient/featureFlagEvaluation.ts

In #320 we added local evaluation of feature flags. Local evaluation calculates the feature flags for the user, but only has user data from the session token. That works for feature flags which are either on or off, but we sometimes want feature flags for a specific group of users, like the AI team or external testers
This work:
- Adds featureFlagGroup to the labs Clerk metadata. We can manually populate this with `ai-team` for the team
- Passes the `featureFlagGroup` into the feature flag evaluation, so that we can calculate the user's flags without needing their email address
Testing:
- See that the [download-all-button](https://eu.posthog.com/project/8837/feature_flags/35349) feature flag is enabled for the group `ai-team`
- Log in with a user with `ai-team` set in clerk metadata (I've …

feat: use featureFlagGroup claim for feature flags

---

README.md
packages/db/scripts/import-export/db_seed.sh

- update docs to reflect local db using port 8432

chore: update docs for local db port 8432

---

apps/nextjs/src/components/AppComponents/Chat/chat-history.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/clear-history.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/sidebar-actions.stories.tsx

At the moment all the stories are within the Chat folder. Half of them relate to the sidebar so it made sense to me to split them out
I thought about moving the actual components into a sidebar subfolder, but I don't know if there's a method to our flat chat component folder

chore: create sidebar storybook folder

---

packages/api/src/router/chats.ts

- The "prisma" import is missing from this file because we have a global prisma type definition in packages/db/client

fix: add missing prisma import

---

apps/nextjs/next.config.js
apps/nextjs/src/app/layout.tsx
apps/nextjs/src/app/styles-registry.tsx

In #337 I noticed that the initial render for our app is always blank. I had a suspicion that this would be hiding some surprises
If you load that page without JS enabled you'll see that the initial render is missing the styled components styling. I've followed the [official guide](https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components) to integration styled components, and checked that it's the same approach the OWA uses

fix: set up server side styled-components

---

packages/api/src/router/testSupport/prepareUser.ts

I noticed in Clerk that we're recycling a small number of test users at the moment. Maybe 15 or so. Looking at the code for the test user pool, it's because some test users have been created but have no lastActiveAt. They then get sorted at the end of the clerk response after the most recently active users
This PR takes a different approach to cleanup:
- Filter staging users by whether the have a test email address
- Sort test users by lastActiveAt OR createdAt
- Delete one of the oldest 8 users (to reduce conflicts between simultaneous runs)

test: delete test users with null activeAt

---

apps/nextjs/src/lib/feature-flags/bootstrap.ts
packages/core/src/analytics/posthogAiBetaServerClient/featureFlagEvaluation.ts
packages/logger/index.ts

Just a small one. I noticed that I'd accidentally created both `feature-flags` and `analytics:feature-flags` loggers

chore: unify feature flag loggers

---

packages/db/prisma/migrations/20241105095800_rag_schema/migration.sql
packages/db/prisma/schema.prisma

- adds 'rag' schema
- minor fixes to 'ingest' tables

feat: add rag schema (migration)

---

apps/nextjs/src/components/AppComponents/Chat/sidebar-actions.stories.tsx
apps/nextjs/src/lib/hooks/use-sidebar.tsx

I found that these storybook interactions weren't working as the first render was empty. After some digging, I found that that sidebar provider renders the whole page as null on its first render while it's loading from localstorage
This means that all of our pages have been rendering as a blank page, then updating to have content
It also means that in non-dev nextjs builds, the initial server render was wild! Huge icons and other problems from the lack of styling. I've based this PR on #341 to fix that
- The sidebar opens and closes as expected
- The general page UI hasn't started flashing or shifting when reloading the page

fix: null render in sidebar provider

---

apps/nextjs/src/lib/feature-flags/bootstrap.ts

Pingdom was failing for the homepage as we started to require a cookie header

fix: allow requests without a cookie header

---

apps/nextjs/src/middlewares/auth.middleware.ts

- Cron job was being redirected to clerk login page, this PR adds it to the public route
Fixes #
` curl -H "Authorization: Bearer [CRON_SECRET]" http://localhost:2525/api/cron-jobs/expired-exports`
You should see an update on the cron job not - 
`/sign-in?redirect_url=http%3A%2F%2Flocalhost%3A2525%2Fapi%2Fcron-jobs%2Fexpired-exports%   `

chore: add expired exports cron job to public routes

---

apps/nextjs/src/app/faqs/index.tsx
apps/nextjs/src/components/ContextProviders/Demo.tsx

- Updates email for demo teacher access banner and request a higher limit link in FAQ to hubspot forms
- Dopper secrets updated for RATELIMIT_FORM_URL
Fixes #
/faqs.  - [request a higher limit.](https://share.hsforms.com/118hyngR-QSS0J7vZEVlRSgbvumd)
/alia.   - [contact us for full access](https://share.hsforms.com/1R9ulYSNPQgqElEHde3KdhAbvumd) - with demo account enabled

feat: link to hubspot form from requests for full access and higher rate - AI-626 AI-627

---

apps/nextjs/.storybook/decorators/RadixThemeDecorator.tsx
apps/nextjs/.storybook/preview.css
apps/nextjs/.storybook/preview.tsx
apps/nextjs/src/app/aila/[id]/download/DownloadView.stories.tsx
apps/nextjs/src/app/aila/[id]/download/DownloadView.tsx
apps/nextjs/src/app/aila/[id]/share/index.stories.tsx
apps/nextjs/src/app/aila/help/index.stories.tsx
apps/nextjs/src/app/aila/help/index.tsx
apps/nextjs/src/app/faqs/index.stories.tsx
apps/nextjs/src/app/home-page.stories.tsx
apps/nextjs/src/app/legal/[slug]/legal.stories.tsx
apps/nextjs/src/app/prompts/prompts.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-start.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/header.tsx

Adds stories for pages under /aila:
- Start chat
- Share
- Download
This doesn't include any coverage of the main chat page, as that will be broken down into smaller stories
Work required to make this happen:
- Fix styles for radix-ui in storybook
- Add DialogProvider to default storybook providers
- Remove autodocs plugin from page stories - a page is a high level happy path so doesn't tend to have variants
View the storybook and the visual changes here
Non-technical reviewers need to go here:

test: stories for aila routes

---

apps/nextjs/src/app/sign-in/[[...sign-in]]/page.tsx

- This attempts to fix an issue where the sign in page was rendering with a different number of hooks
- If the user is logged in and visits /sign-in it redirects to /
Fixes [Sentry issue 3875705](https://oak-national-academy.sentry.io/issues/3875705/?query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0)

fix: hook error on sign-in page

---

apps/nextjs/package.json
apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/LessonPlanProgressDropdown.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/MobileExportButtons.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/MobileExportButtons.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/index.stories.tsx
apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
apps/nextjs/src/components/ContextProviders/Demo.tsx
pnpm-lock.yaml

Stories for:
- LessonPlanDisplay: The right hand side view that pulls it all together
- ExportButtons
- MobileExportButtons: These are extracted from LessonPlanDisplay
- DropDownSection: Including variants for different states, content, and for the modify dropdown
These components use the ChatContext, so I've specified a mock context in each file. If we find we're doing this a lot and that there are some consistent use cases we can find a reusable pattern later
- There's a snapshot to show a collapsed section. That needed a `play` function to click the component. In both the "docs" page and chromatic I had to add a 50ms timeout before clicking
- The mobile export buttons only render on mobile, so I had to specify a mobile viewport
You can view the changes [in …

test: stories for right hand side of lesson planner

---

apps/nextjs/src/components/AppComponents/Chat/ui/codeblock.tsx
apps/nextjs/src/components/AppComponents/Chat/user-or-login.tsx
apps/nextjs/src/components/AppComponents/FeedbackForms/ModerationFeedbackForm.tsx
apps/nextjs/src/components/AppComponents/common/SingleGeneration/GenerationInputAndText.tsx
apps/nextjs/src/components/ContextProviders/AnalyticsProvider.tsx

- Some small sonar issues that have been flagged

fix: minor sonar issues

---

apps/nextjs/src/components/AppComponents/GetInTouchBox.tsx

The help page renders a help email in the server render. Cloudflare obfuscates this and provides some JS to render it with JS. Our CSP is blocking that script
This PR emulates what cloudflare is doing

fix: help page cloudflare email

---

apps/nextjs/src/components/DialogControl/ContentOptions/ModalFooterButtons.tsx
apps/nextjs/src/components/Feedback/index.tsx

- I accepted a Sonar rule to not have positive integer tabindex values
- This changed UX for keyboard navigation
- So this reverts it and we can address this in a different way later

fix: revert tabindex change

---

packages/eslint-config-custom/index.js
packages/eslint-config-custom/package.json
pnpm-lock.yaml

- We have an ongoing issue with cyclic dependencies sometimes causing trouble
- This adds a linting rule (set to warn) which will flag any cyclical dependencies so we can fix them
[Rule definition and explanation](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md)
Note:
"This rule is comparatively computationally expensive. If you are pressed for lint time, or don't think you have an issue with dependency cycles, you may not want this rule enabled."
We may want to only have this turned on with an environment variable if it slows down linting.

chore: add check for cyclic dependencies

---

apps/nextjs/src/lib/hooks/use-sidebar.tsx
packages/exports/src/gSuite/docs/populateDoc.ts

- Addresses a sonar issue complaining that the props of the sidebar provider change each render

fix: memoize the sidebar context provider's value

---

apps/nextjs/src/components/AppComponents/Chat/button-scroll-to-bottom.tsx
apps/nextjs/src/components/AppComponents/Chat/ui/button.tsx
apps/nextjs/src/components/AppComponents/GetInTouchBox.tsx
apps/nextjs/src/components/AppComponents/QuizDesigner/QuizQuestionRow/Answers.tsx
apps/nextjs/src/components/AppComponents/download/DownloadButton.tsx
apps/nextjs/src/components/DialogControl/ContentOptions/DemoInterstitialDialog.tsx
apps/nextjs/src/components/DialogControl/ContentOptions/ReportContentDialog.tsx
packages/api/src/router/lesson.ts
packages/core/src/models/generations.ts
packages/core/src/models/prompts.ts
packages/core/src/rag/index.ts
packages/db/scripts/import-export/validate_data.ts

- Addresses a handful more sonar issues marked maintain

fix: sonar maintain issues #4

---

apps/nextjs/src/components/AppComponents/Chat/markdown.tsx
apps/nextjs/src/components/DialogControl/ContentOptions/ReportContentDialog.tsx

- Fixes a sonar complaint about defining components inline

fix: do not define components inline

---

apps/nextjs/src/app/admin/aila/[chatId]/view.tsx
apps/nextjs/src/components/AppComponents/FeedbackForms/ModerationFeedbackForm.tsx

- Fixes a small issue with using an array for the key of a repeated set of items
- Fixes a missing "void"s in the same files

fix: do not use array index for key / use void for onSubmit

---

apps/nextjs/src/components/AppComponents/Chat/markdown.tsx
apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
apps/nextjs/src/lib/hooks/use-sidebar.tsx

- Minor fixes for Sonar
- nanoid is deprecated in the "ai" package
- When destructuring a useState, the getter and setter should use a consistent naming convention

fix: sonar minors #5

---

sonar-project.properties

- Sets exclusion for SQL and .py files
- Sets project languages
Gets rid of this horrible warning

chore: set sonar languages

---

packages/aila/src/features/moderation/AilaModeration.ts
packages/aila/src/features/moderation/moderators/OpenAiModerator.ts
packages/core/src/models/moderations.ts
packages/core/src/utils/ailaModeration/moderationSchema.ts
packages/db/prisma/migrations/20241202151820_moderation_scores/migration.sql
packages/db/prisma/schema.prisma

- store the scores we get back from the moderation agent
- **Note: contains migration**

fix: moderation persist scores [AI-696]

---

apps/nextjs/src/components/AppComponents/Chat/chat-left-hand-side.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-panel.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-quick-buttons.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-quick-buttons.tsx
apps/nextjs/src/components/AppComponents/Chat/prompt-form.tsx
apps/nextjs/src/lib/analytics/lessonPlanTrackingContext.tsx

- Rename `isEmptyScreen` to `hasMessages`, as the original name seems to be the opposite of the behaviour?
- Infer `hasMessages` from chat context rather than props
- Add stories for the different quick actions states

test: chat quick buttons stories

---

sonar-project.properties

- Currently we get penalised in Sonar for code duplication in storybook files
- This adds .stories.ts{x} to our list of exclusions for duplication calculation

chore: remove stories files from code duplication calculations

---

apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/action-button-wrapper.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/add-additional-materials-button.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/chat-section.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/flag-button.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/modify-button.tsx
apps/nextjs/src/data/lessonSectionTitlesAndMiniDescriptions.ts

- Uses the LessonPlanSectionWhileStreaming type in favour of `Record<string, unknown> | string | Array<unknown>;`

chore: use LessonPlanSectionWhileStreaming type

---

packages/eslint-config/src/rules.mjs

- Temporarily disables two eslint rules which seem to be causing lots of false positives
- Adds a rulesToDecideOn section in the eslint config:
```
"@typescript-eslint/no-unsafe-assignment": "off"
"@typescript-eslint/no-unsafe-call": "off"
```

fix: temporarily disable no unsafe rules

---

apps/nextjs/.storybook/chromatic.ts
apps/nextjs/.storybook/preview.tsx
apps/nextjs/src/app/aila/[id]/download/DownloadView.stories.tsx
apps/nextjs/src/app/aila/[id]/share/index.stories.tsx
apps/nextjs/src/app/aila/help/index.stories.tsx
apps/nextjs/src/app/faqs/index.stories.tsx
apps/nextjs/src/app/home-page.stories.tsx
apps/nextjs/src/app/legal/[slug]/legal.stories.tsx
apps/nextjs/src/app/legal/account-locked/account-locked.stories.tsx
apps/nextjs/src/app/prompts/prompts.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-start.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/index.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/header.stories.tsx
apps/nextjs/src/components/Onboarding/AcceptTermsForm.stories.tsx
apps/nextjs/src/components/Onboarding/LegacyUpgradeNotice.stories.tsx

- Sets the default chromatic viewport to a named "desktop" mode rather than the implicit default "1200px"
- This will give all the current 1200px snapshots a fresh history, so there will be a large diff in the review UI for this switchover. I've approved this already

test: remove legacy chromatic mode and use desktop as default

---

apps/nextjs/src/app/aila/page-contents.tsx

- Removes the key from the chat provider
- This stops it re-rendering when the chat gets an ID for the first time

fix: remove key from chat provider

---

.dependency-cruiser.cjs
.gitignore
package.json
pnpm-lock.yaml

- Adds [Dependency Cruiser](https://www.npmjs.com/package/dependency-cruiser)
- This allows us to statically analyse the dependencies in the project and find issues like:
- Circular dependencies
- Dev dependencies being used when they should be production
- Orphan code that is no longer used
This just adds the package and we can run it locally with `pnpm deps`
It also makes a graph which is fun: `pnpm deps:graph` but a bit hard to understand at the moment!

chore: add dependency cruiser

---

packages/core/src/prompts/lesson-assistant/parts/interactingWithTheUser.ts

- currently in the prompt example response, we provide only 3 relevant lesson titles. Likely this confuses matters, and will lead to us sometimes only showing the user 3 lessons.
- this PR adds a 4th and 5th title, making it more likely that the user will be presented with all 5 lessons.

fix: improve chances of showing 5 relevant plans

---

apps/nextjs/src/components/AppComponents/Chat/Chat/hooks/useProgressForDownloads.ts
apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/chat-section.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/LessonPlanProgressDropdown.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/index.tsx
apps/nextjs/src/data/lessonSectionTitlesAndMiniDescriptions.ts
apps/nextjs/src/hooks/useDemoLocking.ts
apps/nextjs/src/lib/lessonPlan/organiseSections.ts
apps/nextjs/src/lib/lessonPlan/sectionsInOrder.ts
packages/aila/src/features/americanisms/AilaAmericanisms.ts
packages/aila/src/features/persistence/adaptors/prisma/index.ts
packages/aila/src/protocol/schema.ts
packages/core/src/prompts/lesson-assistant/parts/interactingWithTheUser.ts

- LessonPlanKeys plural should be LessonPlanKey singular, based on the principle of least surpriste
- Renames this globally 
- Type-only update, no UX changes

fix: rename LessonPlanKeys to LessonPlanKey

---

apps/nextjs/.storybook/chromatic.ts
apps/nextjs/.storybook/decorators/ChromaticValidationDecorator.tsx
apps/nextjs/.storybook/preview.tsx
apps/nextjs/jest.config.mjs
apps/nextjs/src/components/AppComponents/Chat/Chat/ChatModerationDisplay.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-history.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-lhs-header.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-list/demo-limit-message.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-list/in-chat-download-buttons.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-message/ChatMessagePart.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-message/index.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-panel.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-quick-buttons.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-start-form.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/clear-history.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/index.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/LessonPlanProgressDropdown.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/LessonPlanProgressDropdown.test.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/index.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/guidance-required.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/header.stories.tsx
apps/nextjs/src/components/AppComponents/Chat/sidebar-actions.stories.tsx
apps/nextjs/src/components/DialogControl/DialogContents.stories.tsx
apps/nextjs/src/components/Footer.stories.tsx
apps/nextjs/src/components/Header.stories.tsx
apps/nextjs/src/components/Onboarding/TermsContent.stories.tsx
apps/nextjs/src/components/SignUpSignInLayout.stories.tsx

In storybook, Chromatic is configured through the parameters object:
```
modes: {
desktop: { viewport: "desktop" },
},
```
We provide a default with just the desktop mode, and then stories can add their own modes to the parameters object. The problem is that Storybook merges values in parameters, which means that there's no way for us to remove the desktop mode for a component which is only relevant on mobile
- Remove default chromatic mode from preview.tsx
- Add explicit chromatic viewport config to each story file
- Add ChromaticValidationDecorator to ensure that chromatic config is set
- Fix config for mobile-wide chromatic mode

test: don't force desktop chromatic mode for all stories

---

apps/nextjs/tests-e2e/tests/modifiy-lesson.test.ts

This test has slowed a bit. It first became flaky and then has recently begun to time out (on PRs and main)
In #472 I tried to speed up test LLM fixtures, but it didn't solve the problem. The quick fix to unblock is to extend the timeout

test: increase modify-lesson test timeout

---

packages/exports/src/dataHelpers/prepLessonForSlides.ts
packages/exports/src/dataHelpers/prepLessonPlanForDocs.ts
packages/exports/src/dataHelpers/prepQuizForDocs.ts
packages/exports/src/dataHelpers/prepWorksheetForSlides.ts

- These data prep functions for exports are marked as async
- Use Promise.resolve to retain the expected async behaviour without changing the signature of each function
- Not user-facing

fix: async data prep functions should use Promise.resolve

---

apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
apps/nextjs/src/components/ContextProviders/ChatProvider.tsx

I've been finding that the frontend has been getting in a render loop that calls `getChat` constantly. @JBR90 worked out that #459 was probably the PR that introduced it
I've found that `initialMessages` was different on each render, which might cause useChat to reload and trigger another tRPC request
I've also been finding that the AI SDK calls like `append` aren't stable. This doesn't seem to completely fix that, though changing `initialMessages` could be the cause
Fixes #
1. Open the chat page for an existing lesson plan
2. Look at the console

fix: use stable initialMessages for useChat

---

apps/nextjs/package.json
apps/nextjs/src/components/AppComponents/Chat/chat-right-hand-side-lesson.tsx
apps/nextjs/src/components/ContextProviders/ChatProvider.tsx
apps/nextjs/src/stores/chatStore/hooks.ts
apps/nextjs/src/stores/chatStore/index.ts
apps/nextjs/src/stores/chatStore/parsing.ts
apps/nextjs/src/stores/chatStore/types.ts
packages/logger/index.ts
pnpm-lock.yaml

- We're trying out [Zustand](https://zustand.docs.pmnd.rs/getting-started/introduction) for state management. We don't have a good pattern for centralised or component-local state at the moment
- With Zustand we can
- Gain control over data changes like chat messages streaming from the backend
- Subscribe to slices of the state tree to only re-render components that need to change
- Avoid challenges of chained useEffect/useState/useMemo for complex behaviour
- Make logic (global or component-specific) easily testable without rendering components
- Modularise the behaviours in this project to help with other AI projects across Oak
This pr:
- Adds the "chat" store using zustand
- Syncs chat data into the chat store
- Parses messages to useful structures when adding to the store, not at …

refactor: add zustand mirror for parsed chat messages

---

packages/aila/src/core/quiz/apiCallingUtils.ts
packages/aila/src/core/quiz/rerankers/AilaQuizReranker.ts

- use remeda `pick` to get lesson plan subset
- improve types on `apiCallingUtils` (though curerntly this isn't called anywhere so haven't checked that the new types align with what the caller expects)

chore: maths quiz tighter types

---

apps/nextjs/src/stores/chatStore/index.ts
apps/nextjs/src/stores/zustandHelpers.ts
packages/logger/index.ts

A small change taken from the lesson plan store PR
I think that logging the full store contents could be keeping objects in memory after they're no longer needed. I also found that it was difficult to tell which values had changed in each update

refactor: log store changes by key

---

.github/workflows/sonarcloud.yml
.github/workflows/test.yml

The `SonarSource/sonarcloud-github-action` is deprecated. The newer, drop in replacement, `SonarSource/sonarqube-scan-action` is available.
- Moved from `sonarcloud-github-action` to `sonarqube-scan-action`
- Moved from using `master` as a version to a specific version (to stop any breaking changes immediately impacting project workflows)
Fixes ENG-1129
1. Check SonarQube scans are running successfully.

chore: update the SonarQube action in GitHub workflows

---

packages/aila/src/protocol/schema.ts

In #523 I created LessonPlanKeySchema. I didn't include `basedOn`, which causes zod to fail to parse if you select a lesson from rag

fix: add basedOn to LessonPlanKeySchema

---

apps/nextjs/.storybook/decorators/ChatStoreDecorator.tsx
apps/nextjs/src/app/aila/page-contents.tsx
apps/nextjs/src/stores/AilaStoresProvider.tsx
apps/nextjs/src/stores/lessonPlanStore/index.ts
apps/nextjs/src/stores/lessonPlanStore/stateActionFunctions/handleMessagesUpdated.ts
apps/nextjs/src/stores/lessonPlanStore/stateActionFunctions/handleRefetch.ts
apps/nextjs/src/utils/trpc.tsx

The lesson plan store supports applying patches like `useTemporaryLessonPlanWithStreamingEdits`, but it doesn't have any logic for replacing the temporary lesson plan with a stable version from the API
This PR adds a `refetch` function which runs when the AI SDK stops streaming

feat: refetch lesson plan when streaming completes

---

apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.tsx
apps/nextjs/src/components/AppComponents/Chat/lesson-plan-section/index.tsx
apps/nextjs/src/stores/lessonPlanStore/selectors.ts

In recent changes to lesson plan rendering we stopped passing the lessonPlan into section components with prop drilling, and moved instead to fetching each section from the lesson plan store. This broke the experimental lesson plan functionality which was replacing lesson plan sections in LessonPlanDisplay

fix: maths lesson plan overrides

---

apps/nextjs/src/app/aila/[id]/page.tsx
apps/nextjs/src/app/aila/page.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-left-hand-side.tsx
apps/nextjs/src/stores/chatStore/index.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleExecuteQueuedAction.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleScrollToBottom.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleStreamingFinished.ts
packages/eslint-config/src/rules.mjs
packages/ingest/src/captions/getCaptionsByFileName.ts
packages/rag/lib/search/search.test.ts

Stef and Joe did some great work with our eslint rules, but some rules were hard to fix while we had the moving target of work in other branches. This PR brings the remaining warning rules into the errors list

chore: move remaining lint warnings to errors

---

apps/nextjs/src/components/HeaderAuth.tsx

currently when a user signs into OWA and subsequently clicks the "Sign in" link in Aila (I.e they had the page open in another tab) they're presented with the error
"You're currently in single session mode. You can only be signed into one account at a time."
This appears to be caused by navigating to the page through the Next router. Replacing it with a plain anchor appears to trigger the expected signed-in check and redirect the user back to the app where they are signed in.
1. When signed out
2. Open labs
3. Open /sign-in in another tab
4. Sign in
5. Return to the first tab and click "Sign in"
6. Try to sign in
7. You should be redirected to the home page
How it used to look:
https://github.com/user-attachments/assets/a9f11e3d-0ebd-4817-a50d-d7fa5f24a52d …

fix: next router skipping signed-in check

---

apps/nextjs/src/components/PortableText/portableTextComponents.tsx

- Adds bullet style to sanity portable text for legal pages
Check accessibility page has bullets points

fix: bullet styling for portable text

---

packages/aila/src/core/chat/AilaStreamHandler.ts

- await this._chat.handleSettingInitialState(); was being called twice in the stream handler

fix: initial state being called twice

---

apps/nextjs/src/app/api/chat/chatHandler.ts
packages/aila/src/constants.ts
packages/aila/src/core/Aila.ts
packages/aila/src/core/AilaServices.ts
packages/aila/src/core/document/AilaDocument.ts
packages/aila/src/core/document/types.ts
packages/aila/src/core/prompt/builders/AilaLessonPromptBuilder.ts
packages/aila/src/core/types.ts
packages/aila/src/features/rag/AilaRag.ts
packages/aila/src/features/rag/index.ts
packages/aila/src/protocol/schema.ts

- This continues the process of moving to AilaDocument instead of AilaLessonPlan
- Still no migrations - just changing some variable and class names

feat: continue migrating Aila package to support variable documents

---

apps/nextjs/src/components/AppComponents/Chat/AiSdk.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-lessonPlanDisplay.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-panel.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-quick-buttons.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/action-button-wrapper.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/LessonPlanProgressDropdown.tsx
apps/nextjs/src/stores/AilaStoresProvider.tsx
apps/nextjs/src/stores/chatStore/__tests__/executeQueuedActions.test.tsx
apps/nextjs/src/stores/chatStore/__tests__/handleAppend.test.ts
apps/nextjs/src/stores/chatStore/__tests__/handleStop.test.ts
apps/nextjs/src/stores/chatStore/__tests__/setMessages.test.ts
apps/nextjs/src/stores/chatStore/hooks/useChatStoreAiSdkSync.ts
apps/nextjs/src/stores/chatStore/index.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleAilaStreamingStatusUpdated.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleFetchInitialMessages.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleSetMessages.ts
apps/nextjs/src/stores/chatStore/stateActionFunctions/handleStreamingFinished.ts
apps/nextjs/src/stores/chatStore/types.ts
apps/nextjs/src/stores/lessonPlanStore/hooks/useLessonPlanStoreAiSdkSync.ts
apps/nextjs/src/stores/lessonPlanStore/index.ts
apps/nextjs/src/stores/lessonPlanStore/types.ts
apps/nextjs/src/stores/moderationStore/actionFunctions/handleAilaStreamingStatus.ts
apps/nextjs/src/stores/moderationStore/actionFunctions/handleFetchModeration.tsx
apps/nextjs/src/stores/moderationStore/actionFunctions/handleToxicModeration.tsx
apps/nextjs/src/stores/moderationStore/actionFunctions/handleUpdateModerationState.tsx
apps/nextjs/src/stores/moderationStore/index.ts
apps/nextjs/src/stores/moderationStore/types.ts

Following this recommendation: https://tkdodo.eu/blog/working-with-zustand#separate-actions-from-state
Actions don't ever update so we don't need to split them up into individual hooks to reduce renders. Being able to grab all the actions for a store can save us boilerplate
There is a small caveat to this approach: calls like `stores.chat.getState().actions.fetchInitialMessages();` are a bit longer with `.actions` in there, but we generally shouldn't be calling into stores like that too much so it could be some helpful friction
- Move all store actions into an `actions` object
- Add actions hook for each store
- Remove unused `hasFinished` useState

refactor: bundle store actions under a single key

---

packages/aila/src/protocol/jsonPatchProtocol.ts

On a local branch I accidentally disabled structured outputs and I found that the LLM message was in the wrong structure. Specifically, the "prompt" key in the llmMessage type was this shape:
```
message: "Are the learning outcome and learning cycles appropriate for...",
type: "text"
```
When it should have been
```
value: "Are the learning outcome and learning cycles appropriate for...",
type: "text"
```
This is because we were providing the schema for old parts in the prompt:
```
Patch
Prompt
State
Comment
Error
```
Because there wasn't a schema for `LLMMessage`, it tried the structure of the `Prompt` part
- Replace old part types in the schema with the LLMMessage part schema

fix: use llmMessage JSON schema in prompt

---

apps/nextjs/src/app/api/chat/webActionsPlugin.test.ts
packages/aila/src/utils/moderation/moderationErrorHandling.ts
packages/db/prisma/migrations/20250310114619_add_threat_to_safety_violation_source/migration.sql
packages/db/prisma/schema.prisma

- This attributes detected threats as THREAT the safety violation source column in the DB, rather than HELICONE
- Updates the name of the analytics event to be threat_detected instead of helicone_threat_detected
- No user-facing changes
- Migration is required

feat: record THREAT in the database rather than HELICONE

---

package.json
packages/eslint-config/package.json
packages/eslint-config/src/index.mjs
pnpm-lock.yaml

- Updates turbo to 2.4.4
- Adds linting for the turbo.json using the default linting package

chore: bump turbo to 2.4.4 and add linting for turbo.json

---

packages/aila/src/protocol/jsonPatchProtocol.ts
packages/core/src/prompts/lesson-assistant/parts/protocol.ts

We've seen an increase in issues in the LLM response. One example is that it's referring to sections by their camelcase key names. This could relate to us adding those key names in a JSON schema change

revert: revert prompt schema alignment

---

.github/workflows/test.yml

Our jest github action has been [failing today](https://github.com/oaknational/oak-ai-lesson-assistant/actions/runs/14035634597/job/39292884714?pr=623#step:8:163) after an automatic update to [node v20.19](https://nodejs.org/en/blog/release/v20.19.0). This version enables `require(esm)` by default, which breaks jest v29. See https://github.com/jestjs/jest/pull/15447. The jest fix is still in alpha, so for now let's pin the node version at v20.18 which we know to work

chore: limit test GH action to node v20.18 to fix jest v29

---

apps/nextjs/package.json
package.json
pnpm-lock.yaml

In #593 we added cursor-tools. That has a dependency on the `playwright` package. We use `@playwright/test` which also depends on `playwright`, but needs a matching version
In this PR I've pinned the playwright version so they line up again. The alternative is to remove cursor-tools and install it per dev machine

test: align @playwright/test and playwright package versions

---

packages/aila/src/core/AilaServices.ts
packages/aila/src/core/chat/AilaChat.ts
packages/aila/src/core/chat/AilaStreamHandler.ts
packages/aila/src/core/quiz/generators/BaseQuizGenerator.ts
packages/aila/src/lib/agents/agents.ts
packages/aila/src/lib/agents/compatibility/streamHandling.ts
packages/aila/src/lib/agents/interact.ts
packages/aila/src/lib/agents/lessonPlanSectionGroups.ts
packages/aila/src/lib/agents/messageToUser.ts
packages/aila/src/lib/agents/preRoutingLogic.ts
packages/aila/src/lib/agents/promptAgentHandler.ts
packages/aila/src/lib/agents/prompts/messageToUserInstructions.ts
packages/aila/src/lib/agents/prompts/routerInstructions.ts
packages/aila/src/lib/agents/rag/fetchReleventLessons.agent.ts
packages/aila/src/lib/agents/router.ts
packages/aila/src/protocol/schema.ts
packages/rag/getRagLessonPlansByIds/getRagLessonPlansByIds.ts
packages/rag/index.ts

Fixes #
1. Go to https://oak-ai-lesson-assistant-nlkirxqw4.vercel-preview.thenational.academy
{screenshots}
{screenshots}

feat: add rag and basedOn to agentic model [AI-1152]

---

packages/core/src/utils/slack.ts

- Adds a link to the user in the Aila admin section
- Get your user banned 
- Check the alert in Slack
- There should be a button with label "Aila admin user"
- Clicking that link should take you to the [Aila admin user page](https://github.com/oaknational/oak-ai-lesson-assistant/pull/662), where you can remove safety violations

fix: add admin user button to slack alert when user banned

---

apps/nextjs/src/app/api/cron-jobs/clerk-user-cleanup/route.ts
apps/nextjs/src/app/api/cron-jobs/expired-exports/route.ts
apps/nextjs/src/app/api/cron-jobs/google-drive-size-quota/route.ts

• Adds `export const dynamic = 'force-dynamic';` to all three cron job API routes
• Prevents Next.js from attempting static rendering of routes that access dynamic request data
• Fixes production build errors where Next.js tries to statically render routes with authorization headers, search params, or env checks

fix: force dynamic rendering for cron job routes

---

packages/aila/src/core/prompt/builders/AilaLessonPromptBuilder.ts
packages/aila/src/features/persistence/AilaPersistence.ts
packages/aila/src/features/rag/AilaRag.ts
packages/aila/src/lib/agents/agents.ts
packages/aila/src/lib/agents/promptAgentHandler.ts
packages/aila/src/lib/agents/prompts/shared/examplesFromSimilarLessons.test.ts
packages/aila/src/lib/agents/prompts/shared/examplesFromSimilarLessons.ts
packages/aila/src/protocol/schema.ts
packages/exports/src/schema/input.schema.ts

- the latest ingested lesson plans have **topic** as `null`, as agreed with HB, since there currently isn't a clear and consistent way we're handling 'topic'
- same goes for **basedOn** and **additionalMaterials**
- this PR changes the schema to allow 'topic' to be null, which will then mean we can see the latest ingested lesson plans in the new RAG schema
- it also refactors the 'examplesFromSimilarLessons` function and adds a test for it
AI-1337
- **Non-agentic Aila should work as per usual**
- **Test for agentic Aila:**
1. Create a maths lesson plan, e.g. "circles for ks3"
2. Once confirming title, ks, subject,, you should see a list of lessons offered to base your lesson on
3. That is all

chore: make 'topic' nullable [AI-1337]

---

apps/nextjs/src/app/aila/[id]/share/index.tsx
apps/nextjs/src/components/AppComponents/Chat/drop-down-section/drop-down-section-content.tsx
apps/nextjs/src/components/AppComponents/Chat/lesson-plan-section/index.tsx
apps/nextjs/src/components/AppComponents/Chat/markdown.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/MultipleChoiceQuestion.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/index.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/shuffle.ts
apps/nextjs/src/components/AppComponents/SectionContent/index.stories.tsx
apps/nextjs/src/components/AppComponents/SectionContent/index.tsx
apps/nextjs/src/components/AppComponents/static-lesson-plan-renderer.stories.tsx
apps/nextjs/src/components/AppComponents/static-lesson-plan-renderer.tsx
apps/nextjs/src/stores/chatStore/hooks/useChatStoreAiSdkSync.ts
packages/aila/src/protocol/schemas/quiz/conversion/quizV1ToV2.test.ts
packages/aila/src/protocol/schemas/quiz/conversion/quizV1ToV2.ts
packages/aila/src/protocol/schemas/quiz/quizV2.ts

Implement quiz V2 rendering components to display existing V1 quiz data. Both the chat interface and share page use the same rendering components but with different title displays - chat uses collapsible sections while share page shows static titles with tooltips.
- Add `SectionContent` component that validates V1 quiz data and converts to V2 for rendering
- Create `QuizSection` component with Oak styling (checkboxes, answer labels, dynamic instructions)
- Refactor shared rendering: `ChatSection` → `StaticSection` and move out of Chat folder  
- Add storybook stories for testing components
- Remove unused `feedback` field from QuizV2 schema

feat: [AI-1374] implement quiz v2 multiple choice components

---

packages/aila/src/protocol/schemas/quiz/conversion/__snapshots__/rawQuizIngest.test.ts.snap
packages/aila/src/protocol/schemas/quiz/conversion/rawQuizIngest.test.ts
packages/aila/src/protocol/schemas/quiz/conversion/rawQuizIngest.ts
packages/aila/src/protocol/schemas/quiz/fixtures/rawQuizFixture.ts
packages/aila/src/protocol/schemas/quiz/rawQuiz.ts

- Add `convertRawQuizToV2` function to convert Oak's raw quiz format to Quiz V2 structure
- Extract markdown content from complex stem arrays with text and image items
- Preserve image attribution metadata throughout conversion
- **NEW**: Support alt text extraction from images when available
- **NEW**: Extract hints from raw quiz questions
- Works directly with snake_case data from Oak curriculum (no camelCase conversion needed)
- Converts images to markdown syntax with alt text: `\![alt text](secure_url)`
- Extracts attribution from `image_object.metadata.attribution`
- Extracts hints from `rawQuestion.hint` field
- Supports all quiz types: multiple-choice, short-answer, match, order
- Returns clean V2 structure with markdown strings and image attributions at quiz level
**Input (Oak raw …

feat: add convertRawQuizToV2 function for quiz format conversion

---

apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/AnswerBox.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/MatchQuestion.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/MultipleChoiceQuestion.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/OrderQuestion.tsx

- Removed the handwriting wobble effect from quiz answer boxes for a cleaner, more professional appearance
- The wobble effect was created using CSS transforms with slight rotations and translations
- Removed `getWobbleTransform` function from AnswerBox component
- Removed `wobbleOffset` prop from AnswerBoxProps interface
- Removed transform styling from answer boxes
- Updated all quiz question components to stop passing the wobbleOffset prop:
- MultipleChoiceQuestion
- MatchQuestion
- OrderQuestion

fix: remove handwriting wobble effect from quiz answer boxes

---

packages/additional-materials/src/documents/additionalMaterials/promptHelpers.ts
packages/aila/src/protocol/schema.ts
packages/rag/lib/search/parseResult.ts

- Ingested lesson plans will now have cycle3 as optional and broadly speaking won't have length constraints
- This PR updates the RAG search function to reflect that
- It also generally makes Cycle 3 nullable, which I actually thought it should have been already (we have Slides templates for lessons with 1 or 2 cycles) 
_**Note:** it's this last point that is the most substantial change (potential to affect application beyond the maths/agentic capability)_ 
https://www.notion.so/oaknationalacademy/Fix-new-RAG-zod-schema-24126cc4e1b180738046ed321a0dbbc9?source=copy_link

fix: rag lesson schema - cycle3 optional and all without length

---

apps/nextjs/src/app/faqs/index.tsx
apps/nextjs/src/app/legal/account-locked/account-locked.tsx
apps/nextjs/src/components/AppComponents/Chat/chat-panel-disclaimer.tsx
apps/nextjs/src/components/ContextProviders/CookieConsentProvider.tsx
apps/nextjs/src/components/Onboarding/AcceptTermsForm.tsx
apps/nextjs/src/components/Onboarding/TermsContent.tsx
apps/nextjs/src/data/menus.tsx

- Fixed incorrect legal page links that were pointing to outdated Sanity-powered pages on the labs subdomain
- All legal links now correctly point to the official pages on `www.thenational.academy`
- Added `target="_blank"` to all legal links for consistent UX (preserves user context)
Users reported that the privacy policy link was going to the wrong place. Investigation revealed that:
- Some links were pointing to `/legal/*` paths (served from Sanity CMS with outdated content)
- Some links were pointing to `labs.thenational.academy/legal/*` 
- The correct legal pages are hosted at `www.thenational.academy/legal/*`
Updated links in 7 files:
- ✅ Privacy policy → `https://www.thenational.academy/legal/privacy-policy`
- ✅ Cookie policy → `https://www.thenational.academy/legal/cookie-policy` …

fix: update legal page links to point to thenational.academy

---

apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/ShortAnswerQuestion.stories.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/ShortAnswerQuestion.tsx

Support both `{{}}` and `{{ }}` patterns in short answer questions.
Adds Storybook example for `{{ }}` pattern.

fix: short answer placeholder patterns

---

packages/aila/src/protocol/schema.ts
packages/rag/lib/search/search.ts
packages/rag/types.ts

Fixes RAG lesson plan parsing failures that were returning 0 results.
The main issue: We were parding RAG data with CompletedLessonPlanSchemaWithoutLength, where `topic` was required.
- Make topic field nullable to handle legacy data
- Add detailed error logging to identify validation issues
- Throw early when all results fail parsing
- Update RagLogger type to support object logging

fix: resolve RAG parse errors blocking lesson retrieval

---

apps/nextjs/src/components/AppComponents/Chat/markdown.tsx
packages/exports/src/gSuite/docs/replacements/imageReplacements.ts
packages/exports/src/images/constants.ts

At the moment, quiz images are displayed at their original resolution. The problem is that content creators are told to create assets in as high a resolution as they can so that they look sharp in different places and screens. This makes them too large in our exports
Solution:
- Set a max width and height for images in quizzes

feat: set a max width and height for quiz images

---

apps/nextjs/package.json
apps/nextjs/src/components/AppComponents/AdditionalMaterials/StepLayouts/StepOne.tsx
apps/nextjs/src/components/DialogControl/ContentOptions/AdditionalMaterialsStartAgain.tsx
pnpm-lock.yaml

Update: bumps Oak component, dot had removed
~~Fixes the dot seen here. The root cause isn't yet known, but this is how we've patched the other radio buttons. To investigate!~~

fix: fix radio button dot after oak-components update

---

packages/aila/src/core/prompt/builders/AilaLessonPromptBuilder.ts

- just adds a comment for clarification
The situation now is that we have two feature flags that relate two the new RAG schema/Agentic system/Maths recommender:
- **rag-schema-2024-12**: if enabled, sessions that are using the 'mega prompt' flow will fetch RAG data from the new RAG schema. Currently this is disabled for all users. 
- **agentic-aila-may-25**: if enabled, sessions will have `aila.options.useAgenticAila` set to true. Sessions will use the agentic system, which in turn always points at the new RAG schema. Currently enabled for internal users testing maths recommender.

chore: add feature flag comment for 'new rag schema'

---

apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/ShortAnswerQuestion.stories.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/textWithBlanks.test.tsx
apps/nextjs/src/components/AppComponents/SectionContent/QuizSection/textWithBlanks.tsx

In #798, @mikeritson-oak noticed that placeholders like `{{ }}°C` aren't rendered with the underline element. This will fix it
Example here https://672908473f629875f0be294f-pqqsogflpj.chromatic.com/?path=/story/components-quiz-shortanswerquestion--inline-answer-with-degrees

fix: support units other than degrees with placeholders

---

apps/nextjs/src/components/AppComponents/Chat/chat-list/in-chat-download-buttons.tsx
apps/nextjs/src/components/AppComponents/Chat/export-buttons/MobileExportButtons.tsx

- The download button was incorrectly formatter on mobile due to an extra brace
Fixes #AI-1578

fix: extra brace in mobile download URL

---

packages/exports/src/exportSlidesFullLesson.ts
packages/exports/src/gSuite/slides/clearSpeakerNoteTags.ts
packages/exports/src/gSuite/slides/deleteSlides.ts

We don't have an easy way to render inline latex or images in Google Slides. These are only needed in maths and only in quizzes. For now, we can remove starter and exit quizzes from slide exports if the subject is maths
We have some existing export code to remove slides in a document based on a tag in the speaker notes. It looks like we're not actually using that any more as the tags aren't in the template. But we can adapt that approach to tag quiz slides
Fixes #
1. Generate a maths slide file
2. See that the quizzes are missing
3. Generate a non-maths slides file
4. See that the quizzes are there and there are no internal tags in the speaker notes

feat: remove starter and exit quizzes from maths lessons
